In [511]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset

from sklearn.metrics import f1_score, confusion_matrix, classification_report
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold, StratifiedKFold

import os
import pandas as pd
import numpy as np
from tqdm.auto import tqdm
import random
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings(action='ignore') 

device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

In [512]:
file_version = 33
CFG = {
    'EPOCHS': 30,
    'LEARNING_RATE':1e-2,    # 0.01
    'BATCH_SIZE':256,  #256
    'SEED':43,
    'log_transform_turn': 1,  # 로그 트랜스폼을 몇번 돌릴 것인가?
    'skew_cut':0.01,           # 왜도 얼마 이상을 로그값으로 정규화할 것인가?(100이면 안하겠다는 것)
    'vif_cut': 10,           # 다중공선성 vif 얼마 이상을 제거할 것인가?
    'corr_cut': 0.0075,     # 일정 상관관계 이하 칼럼은 드랍
    'outlier_corr_cut': 100,    # 이값 이상의 상관관계를 갖는 칼럼에 대해서만 아웃라이어 제거(100이면 미적용)
    'T_Thresh': 0.3,     # Teacher model train Threshhold 최초 0.35
    'S_Thresh': 0.325,     # Student model train Threshold 최초 0.35
    'reduct' : 'sum',      # sum, mean
    'drop_rate': 0.2,
    
}

In [513]:
import pickle
#불러오기
with open(f"./data/{file_version}_refined_train_X", 'rb') as pickle_filename:
	train_X = pickle.load(pickle_filename)

with open(f"./data/{file_version}_refined_train_y", 'rb') as pickle_filename:
	train_y = pickle.load(pickle_filename)
    
with open(f"./data/{file_version}_refined_val_X", 'rb') as pickle_filename:
	val_X = pickle.load(pickle_filename)

with open(f"./data/{file_version}_refined_val_y", 'rb') as pickle_filename:
	val_y = pickle.load(pickle_filename)     

with open(f"./data/{file_version}_refined_test", 'rb') as pickle_filename:
	test = pickle.load(pickle_filename)

In [514]:
train_y.value_counts()

0.0    10314
1.0      962
Name: Y_LABEL, dtype: int64

In [515]:
test_stage_features = test.columns
test_stage_features

Index(['encoder__x0_COMPONENT2', 'encoder__x0_COMPONENT3',
       'encoder__x0_COMPONENT4', 'encoder__x1_y2', 'encoder__x1_y3',
       'encoder__x1_y4', 'encoder__x1_y5', 'ANONYMOUS_1', 'ANONYMOUS_2', 'AG',
       'CO', 'CR', 'CU', 'FE', 'H2O', 'MN', 'MO', 'NI', 'PQINDEX', 'TI', 'V',
       'V40', 'ZN'],
      dtype='object')

In [516]:
len(test_stage_features)

23

In [517]:
class CustomDataset(Dataset):
    def __init__(self, data_X, data_y, distillation=False):
        super(CustomDataset, self).__init__()
        self.data_X = data_X
        self.data_y = data_y
        self.distillation = distillation
        
    def __len__(self):
        return len(self.data_X)
    
    def __getitem__(self, index):
        if self.distillation:
            # 지식 증류 학습 시
            teacher_X = torch.Tensor(self.data_X.iloc[index])
            student_X = torch.Tensor(self.data_X[test_stage_features].iloc[index])
            y = self.data_y.values[index]
            return teacher_X, student_X, y
        else:
            if self.data_y is None:
                test_X = torch.Tensor(self.data_X.iloc[index])
                return test_X
            else:
                teacher_X = torch.Tensor(self.data_X.iloc[index])
                y = self.data_y.values[index]
                return teacher_X, y

In [518]:
train_dataset = CustomDataset(train_X, train_y, False)
val_dataset = CustomDataset(val_X, val_y, False)
list(train_dataset)[:1]

[(tensor([ 1.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,
           1.0000, -1.0430,  1.0329, -0.1537, -0.4862, -1.1424, -0.4931, -0.0544,
           0.9904, -0.1251,  5.6677, -0.0957,  2.2429,  0.6061, -0.0969, -0.4387,
          -0.2594, -0.2194,  0.4350, -0.3730, -0.4347,  0.8037, -0.6452, -2.0525,
          -0.4578, -0.8064,  1.2249, -0.2640, -0.1545, -1.9767,  0.5502]),
  0.0)]

In [519]:
train_loader = DataLoader(train_dataset, batch_size = CFG['BATCH_SIZE'], shuffle=True)
val_loader = DataLoader(val_dataset, batch_size = CFG['BATCH_SIZE'], shuffle=False)
list(train_loader)[:1] 

[[tensor([[ 0.0000,  0.0000,  0.0000,  ..., -0.1545,  0.1203,  0.9504],
          [ 0.0000,  0.0000,  0.0000,  ..., -0.1545,  0.2165,  0.9341],
          [ 0.0000,  1.0000,  0.0000,  ..., -0.1545,  0.7189, -1.8923],
          ...,
          [ 0.0000,  1.0000,  0.0000,  ..., -0.1545,  2.9139, -0.9509],
          [ 0.0000,  0.0000,  0.0000,  ..., -0.1545,  0.0478,  1.0345],
          [ 0.0000,  1.0000,  0.0000,  ..., -0.1545,  1.1190, -1.6622]]),
  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0

In [520]:
class Teacher(nn.Module):
    def __init__(self):
        super(Teacher, self).__init__()
        self.classifier = nn.Sequential(
            nn.Linear(in_features=train_col_num, out_features=256),
            nn.Dropout(p=CFG['drop_rate']),
            nn.BatchNorm1d(256),
            nn.LeakyReLU(),
            nn.Linear(in_features=256, out_features=1024),
            nn.Dropout(p=CFG['drop_rate']),
            nn.BatchNorm1d(1024),
            nn.LeakyReLU(),
            nn.Linear(in_features=1024, out_features=256),
            nn.Dropout(p=CFG['drop_rate']),
            nn.BatchNorm1d(256),
            nn.LeakyReLU(),
            nn.Linear(in_features=256, out_features=1),
            nn.Sigmoid()
        )
        
    def forward(self, x):
        output = self.classifier(x)
        return output

In [521]:
def train(model, optimizer, train_loader, val_loader, scheduler, device):
    model.to(device)

    best_score = 0
    best_model = None
    
    # Loss Function 정의
    criterion = nn.BCELoss(reduction = CFG['reduct']).to(device)  #BCEWithLogitsLoss
#     criterion = nn.BCEWithLogitsLoss(reduction = CFG['reduct']).to(device)  #BCEWithLogitsLoss

    for epoch in range(CFG["EPOCHS"]):
        train_loss = []
  
        model.train()
        for X, y in tqdm(train_loader):
            X = X.float().to(device)
            y = y.float().to(device)
            
            optimizer.zero_grad()
            
            y_pred = model(X)
            
            loss = criterion(y_pred, y.reshape(-1, 1))  # loss_fn(input, target)
            loss.backward()
            
            optimizer.step()

            train_loss.append(loss.item())

        val_loss, val_score = validation_teacher(model, val_loader, criterion, device)
        print(f'Epoch [{epoch}], Train Loss : [{np.mean(train_loss) :.5f}] Val Loss : [{np.mean(val_loss) :.5f}] Val F1 Score : [{val_score:.5f}]')

        if scheduler is not None:
            scheduler.step(val_score)
            
        if best_score < val_score:
            best_model = model
            best_score = val_score
    print(f"Teacher Train Best Score는 {best_score} 입니다.")
    return best_model 

In [522]:
def competition_metric(true, pred):
    return f1_score(true, pred, average="macro")


def validation_teacher(model, val_loader, criterion, device):
    model.eval()

    val_loss = []
    pred_labels = []
    true_labels = []
    threshold = CFG['T_Thresh']     
    
    with torch.no_grad():
        for X, y in tqdm(val_loader):
            X = X.float().to(device)
            y = y.float().to(device)
            
            model_pred = model(X.to(device))
            
            loss = criterion(model_pred, y.reshape(-1, 1))
            val_loss.append(loss.item())      
            
            model_pred = model_pred.squeeze(1).to('cpu')  # squeeze함수는 차원이 1인 차원을 제거해준다.
            pred_labels += model_pred.tolist()
            true_labels += y.tolist()
        
        #print(pred_labels[0:10])
        # 오일상태는 0: 정상, 1: 이상
        # 어느 임계점 thrshold보다 큰 예측 라벨을 1로 하고, 나머지를 0으로 할 것인가?
        pred_labels = np.where(np.array(pred_labels) > threshold, 1, 0)
        #print(pred_labels[0:10])
        cf = confusion_matrix(true_labels, pred_labels)
        val_f1 = competition_metric(true_labels, pred_labels)
        
        print(cf)
        print(classification_report(true_labels, pred_labels, target_names=["0: 정상", "1: 이상"]))
    return val_loss, val_f1

In [523]:
train_col_num = len(train_X.columns)
test_col_num = len(test.columns)
print(train_col_num, test_col_num) # Drop후 칼럼 갯수 (nn 시작 노드 갯수에 맞춰주기 위해 변수에 담아놓음)

39 23


In [524]:
train_X.columns

Index(['encoder__x0_COMPONENT2', 'encoder__x0_COMPONENT3',
       'encoder__x0_COMPONENT4', 'encoder__x1_y2', 'encoder__x1_y3',
       'encoder__x1_y4', 'encoder__x1_y5', 'encoder__x2_s2', 'encoder__x2_s3',
       'ANONYMOUS_1', 'ANONYMOUS_2', 'AG', 'AL', 'B', 'BA', 'BE', 'CA', 'CD',
       'CO', 'CR', 'CU', 'FE', 'H2O', 'K', 'LI', 'MG', 'MN', 'MO', 'NA', 'NI',
       'PQINDEX', 'S', 'SB', 'SI', 'SN', 'TI', 'V', 'V40', 'ZN'],
      dtype='object')

In [525]:
test_stage_features = test.columns
test_stage_features

Index(['encoder__x0_COMPONENT2', 'encoder__x0_COMPONENT3',
       'encoder__x0_COMPONENT4', 'encoder__x1_y2', 'encoder__x1_y3',
       'encoder__x1_y4', 'encoder__x1_y5', 'ANONYMOUS_1', 'ANONYMOUS_2', 'AG',
       'CO', 'CR', 'CU', 'FE', 'H2O', 'MN', 'MO', 'NI', 'PQINDEX', 'TI', 'V',
       'V40', 'ZN'],
      dtype='object')

In [526]:
test_col_num

23

In [527]:
model = Teacher()
model.eval()
optimizer = torch.optim.Adam(model.parameters(), lr=CFG['LEARNING_RATE'])
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=1, threshold_mode='abs',min_lr=1e-8, verbose=True)
pred_labels = []
true_labels = []

teacher_model = train(model, optimizer, train_loader, val_loader, scheduler, device)

  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2485   93]
 [ 101  140]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.96      0.96      2578
       1: 이상       0.60      0.58      0.59       241

    accuracy                           0.93      2819
   macro avg       0.78      0.77      0.78      2819
weighted avg       0.93      0.93      0.93      2819

Epoch [0], Train Loss : [57.72583] Val Loss : [42.84269] Val F1 Score : [0.77657]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2551   27]
 [ 113  128]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.99      0.97      2578
       1: 이상       0.83      0.53      0.65       241

    accuracy                           0.95      2819
   macro avg       0.89      0.76      0.81      2819
weighted avg       0.95      0.95      0.95      2819

Epoch [1], Train Loss : [42.01717] Val Loss : [42.23782] Val F1 Score : [0.80988]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2533   45]
 [ 111  130]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.98      0.97      2578
       1: 이상       0.74      0.54      0.63       241

    accuracy                           0.94      2819
   macro avg       0.85      0.76      0.80      2819
weighted avg       0.94      0.94      0.94      2819

Epoch [2], Train Loss : [40.59283] Val Loss : [42.72844] Val F1 Score : [0.79756]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2480   98]
 [  95  146]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.96      0.96      2578
       1: 이상       0.60      0.61      0.60       241

    accuracy                           0.93      2819
   macro avg       0.78      0.78      0.78      2819
weighted avg       0.93      0.93      0.93      2819

Epoch [3], Train Loss : [39.13636] Val Loss : [41.11802] Val F1 Score : [0.78230]
Epoch 00004: reducing learning rate of group 0 to 5.0000e-03.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2484   94]
 [  98  143]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.96      0.96      2578
       1: 이상       0.60      0.59      0.60       241

    accuracy                           0.93      2819
   macro avg       0.78      0.78      0.78      2819
weighted avg       0.93      0.93      0.93      2819

Epoch [4], Train Loss : [37.27199] Val Loss : [41.53195] Val F1 Score : [0.78056]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2520   58]
 [ 103  138]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.98      0.97      2578
       1: 이상       0.70      0.57      0.63       241

    accuracy                           0.94      2819
   macro avg       0.83      0.78      0.80      2819
weighted avg       0.94      0.94      0.94      2819

Epoch [5], Train Loss : [35.22237] Val Loss : [40.59759] Val F1 Score : [0.80031]
Epoch 00006: reducing learning rate of group 0 to 2.5000e-03.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2543   35]
 [ 126  115]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.99      0.97      2578
       1: 이상       0.77      0.48      0.59       241

    accuracy                           0.94      2819
   macro avg       0.86      0.73      0.78      2819
weighted avg       0.94      0.94      0.94      2819

Epoch [6], Train Loss : [33.71298] Val Loss : [43.16600] Val F1 Score : [0.77878]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2521   57]
 [ 110  131]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.98      0.97      2578
       1: 이상       0.70      0.54      0.61       241

    accuracy                           0.94      2819
   macro avg       0.83      0.76      0.79      2819
weighted avg       0.94      0.94      0.94      2819

Epoch [7], Train Loss : [32.11523] Val Loss : [42.04130] Val F1 Score : [0.78933]
Epoch 00008: reducing learning rate of group 0 to 1.2500e-03.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2514   64]
 [ 109  132]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.98      0.97      2578
       1: 이상       0.67      0.55      0.60       241

    accuracy                           0.94      2819
   macro avg       0.82      0.76      0.79      2819
weighted avg       0.93      0.94      0.94      2819

Epoch [8], Train Loss : [30.18145] Val Loss : [42.00092] Val F1 Score : [0.78543]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2513   65]
 [ 104  137]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.97      0.97      2578
       1: 이상       0.68      0.57      0.62       241

    accuracy                           0.94      2819
   macro avg       0.82      0.77      0.79      2819
weighted avg       0.94      0.94      0.94      2819

Epoch [9], Train Loss : [29.21376] Val Loss : [41.54294] Val F1 Score : [0.79299]
Epoch 00010: reducing learning rate of group 0 to 6.2500e-04.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2520   58]
 [ 109  132]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.98      0.97      2578
       1: 이상       0.69      0.55      0.61       241

    accuracy                           0.94      2819
   macro avg       0.83      0.76      0.79      2819
weighted avg       0.94      0.94      0.94      2819

Epoch [10], Train Loss : [29.16805] Val Loss : [42.94579] Val F1 Score : [0.79023]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2539   39]
 [ 120  121]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.98      0.97      2578
       1: 이상       0.76      0.50      0.60       241

    accuracy                           0.94      2819
   macro avg       0.86      0.74      0.79      2819
weighted avg       0.94      0.94      0.94      2819

Epoch [11], Train Loss : [28.43515] Val Loss : [43.57581] Val F1 Score : [0.78657]
Epoch 00012: reducing learning rate of group 0 to 3.1250e-04.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2530   48]
 [ 115  126]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.98      0.97      2578
       1: 이상       0.72      0.52      0.61       241

    accuracy                           0.94      2819
   macro avg       0.84      0.75      0.79      2819
weighted avg       0.94      0.94      0.94      2819

Epoch [12], Train Loss : [28.05404] Val Loss : [43.59390] Val F1 Score : [0.78801]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2512   66]
 [ 108  133]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.97      0.97      2578
       1: 이상       0.67      0.55      0.60       241

    accuracy                           0.94      2819
   macro avg       0.81      0.76      0.79      2819
weighted avg       0.93      0.94      0.94      2819

Epoch [13], Train Loss : [26.89463] Val Loss : [42.78947] Val F1 Score : [0.78554]
Epoch 00014: reducing learning rate of group 0 to 1.5625e-04.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2519   59]
 [ 116  125]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.98      0.97      2578
       1: 이상       0.68      0.52      0.59       241

    accuracy                           0.94      2819
   macro avg       0.82      0.75      0.78      2819
weighted avg       0.93      0.94      0.93      2819

Epoch [14], Train Loss : [28.06502] Val Loss : [44.48124] Val F1 Score : [0.77733]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2512   66]
 [ 109  132]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.97      0.97      2578
       1: 이상       0.67      0.55      0.60       241

    accuracy                           0.94      2819
   macro avg       0.81      0.76      0.78      2819
weighted avg       0.93      0.94      0.94      2819

Epoch [15], Train Loss : [27.12811] Val Loss : [43.28948] Val F1 Score : [0.78385]
Epoch 00016: reducing learning rate of group 0 to 7.8125e-05.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2520   58]
 [ 115  126]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.98      0.97      2578
       1: 이상       0.68      0.52      0.59       241

    accuracy                           0.94      2819
   macro avg       0.82      0.75      0.78      2819
weighted avg       0.93      0.94      0.93      2819

Epoch [16], Train Loss : [26.94389] Val Loss : [42.93735] Val F1 Score : [0.77988]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2518   60]
 [ 116  125]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.98      0.97      2578
       1: 이상       0.68      0.52      0.59       241

    accuracy                           0.94      2819
   macro avg       0.82      0.75      0.78      2819
weighted avg       0.93      0.94      0.93      2819

Epoch [17], Train Loss : [27.05686] Val Loss : [43.90573] Val F1 Score : [0.77654]
Epoch 00018: reducing learning rate of group 0 to 3.9063e-05.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2509   69]
 [ 108  133]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.97      0.97      2578
       1: 이상       0.66      0.55      0.60       241

    accuracy                           0.94      2819
   macro avg       0.81      0.76      0.78      2819
weighted avg       0.93      0.94      0.93      2819

Epoch [18], Train Loss : [26.97077] Val Loss : [43.03971] Val F1 Score : [0.78319]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2496   82]
 [ 104  137]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.97      0.96      2578
       1: 이상       0.63      0.57      0.60       241

    accuracy                           0.93      2819
   macro avg       0.79      0.77      0.78      2819
weighted avg       0.93      0.93      0.93      2819

Epoch [19], Train Loss : [26.73820] Val Loss : [43.05131] Val F1 Score : [0.77987]
Epoch 00020: reducing learning rate of group 0 to 1.9531e-05.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2517   61]
 [ 116  125]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.98      0.97      2578
       1: 이상       0.67      0.52      0.59       241

    accuracy                           0.94      2819
   macro avg       0.81      0.75      0.78      2819
weighted avg       0.93      0.94      0.93      2819

Epoch [20], Train Loss : [26.91681] Val Loss : [43.58426] Val F1 Score : [0.77576]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2516   62]
 [ 112  129]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.98      0.97      2578
       1: 이상       0.68      0.54      0.60       241

    accuracy                           0.94      2819
   macro avg       0.82      0.76      0.78      2819
weighted avg       0.93      0.94      0.94      2819

Epoch [21], Train Loss : [26.84963] Val Loss : [43.98248] Val F1 Score : [0.78190]
Epoch 00022: reducing learning rate of group 0 to 9.7656e-06.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2528   50]
 [ 119  122]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.98      0.97      2578
       1: 이상       0.71      0.51      0.59       241

    accuracy                           0.94      2819
   macro avg       0.83      0.74      0.78      2819
weighted avg       0.93      0.94      0.94      2819

Epoch [22], Train Loss : [26.43364] Val Loss : [44.85974] Val F1 Score : [0.77923]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2535   43]
 [ 118  123]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.98      0.97      2578
       1: 이상       0.74      0.51      0.60       241

    accuracy                           0.94      2819
   macro avg       0.85      0.75      0.79      2819
weighted avg       0.94      0.94      0.94      2819

Epoch [23], Train Loss : [26.44312] Val Loss : [44.14396] Val F1 Score : [0.78682]
Epoch 00024: reducing learning rate of group 0 to 4.8828e-06.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2534   44]
 [ 121  120]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.98      0.97      2578
       1: 이상       0.73      0.50      0.59       241

    accuracy                           0.94      2819
   macro avg       0.84      0.74      0.78      2819
weighted avg       0.94      0.94      0.94      2819

Epoch [24], Train Loss : [26.55050] Val Loss : [44.99457] Val F1 Score : [0.78053]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2512   66]
 [ 111  130]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.97      0.97      2578
       1: 이상       0.66      0.54      0.59       241

    accuracy                           0.94      2819
   macro avg       0.81      0.76      0.78      2819
weighted avg       0.93      0.94      0.93      2819

Epoch [25], Train Loss : [26.87015] Val Loss : [43.26525] Val F1 Score : [0.78047]
Epoch 00026: reducing learning rate of group 0 to 2.4414e-06.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2533   45]
 [ 119  122]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.98      0.97      2578
       1: 이상       0.73      0.51      0.60       241

    accuracy                           0.94      2819
   macro avg       0.84      0.74      0.78      2819
weighted avg       0.94      0.94      0.94      2819

Epoch [26], Train Loss : [26.71980] Val Loss : [44.54355] Val F1 Score : [0.78334]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2529   49]
 [ 125  116]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.98      0.97      2578
       1: 이상       0.70      0.48      0.57       241

    accuracy                           0.94      2819
   macro avg       0.83      0.73      0.77      2819
weighted avg       0.93      0.94      0.93      2819

Epoch [27], Train Loss : [26.28913] Val Loss : [45.82795] Val F1 Score : [0.76909]
Epoch 00028: reducing learning rate of group 0 to 1.2207e-06.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2530   48]
 [ 119  122]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.98      0.97      2578
       1: 이상       0.72      0.51      0.59       241

    accuracy                           0.94      2819
   macro avg       0.84      0.74      0.78      2819
weighted avg       0.93      0.94      0.94      2819

Epoch [28], Train Loss : [26.00799] Val Loss : [45.20518] Val F1 Score : [0.78086]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2524   54]
 [ 126  115]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.98      0.97      2578
       1: 이상       0.68      0.48      0.56       241

    accuracy                           0.94      2819
   macro avg       0.82      0.73      0.76      2819
weighted avg       0.93      0.94      0.93      2819

Epoch [29], Train Loss : [26.42651] Val Loss : [45.88626] Val F1 Score : [0.76327]
Epoch 00030: reducing learning rate of group 0 to 6.1035e-07.
Teacher Train Best Score는 0.8098786414314838 입니다.


In [528]:
PATH1 = f"./models/{file_version}_teacher_net.pth"
torch.save(teacher_model.state_dict(), PATH1)

In [529]:
teacher_model = Teacher()
teacher_model.load_state_dict(torch.load(PATH1))
teacher_model

Teacher(
  (classifier): Sequential(
    (0): Linear(in_features=39, out_features=256, bias=True)
    (1): Dropout(p=0.2, inplace=False)
    (2): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): LeakyReLU(negative_slope=0.01)
    (4): Linear(in_features=256, out_features=1024, bias=True)
    (5): Dropout(p=0.2, inplace=False)
    (6): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): LeakyReLU(negative_slope=0.01)
    (8): Linear(in_features=1024, out_features=256, bias=True)
    (9): Dropout(p=0.2, inplace=False)
    (10): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (11): LeakyReLU(negative_slope=0.01)
    (12): Linear(in_features=256, out_features=1, bias=True)
    (13): Sigmoid()
  )
)

In [530]:
class Student(nn.Module):
    def __init__(self):
        super(Student, self).__init__()
        self.classifier = nn.Sequential(
            nn.Linear(in_features=test_col_num, out_features=128),
            nn.Dropout(p=CFG['drop_rate']),
            nn.BatchNorm1d(128),
            nn.LeakyReLU(),
            nn.Linear(in_features=128, out_features=512),
            nn.Dropout(p=CFG['drop_rate']),
            nn.BatchNorm1d(512),
            nn.LeakyReLU(),
            nn.Linear(in_features=512, out_features=128),
            nn.Dropout(p=CFG['drop_rate']),
            nn.BatchNorm1d(128),
            nn.LeakyReLU(),
            nn.Linear(in_features=128, out_features=1),
            nn.Sigmoid()
        )
        
    def forward(self, x):
        output = self.classifier(x)
        return output

In [531]:
# distillation Function 정의

def distillation(student_logits, labels, teacher_logits, alpha, T):
    
    student_loss = nn.BCELoss(reduction = CFG['reduct'])(student_logits, labels.reshape(-1, 1)) #BCEWithLogitsLoss
#     student_loss = nn.BCEWithLogitsLoss(reduction = CFG['reduct'])(student_logits, labels.reshape(-1, 1)) #BCEWithLogitsLoss

    distillation_loss = nn.KLDivLoss(reduction='batchmean')(F.log_softmax(student_logits/T, dim=1), F.softmax(teacher_logits/T, dim=1)) * (T * T)
    
    return alpha * student_loss + (1-alpha) * distillation_loss

def distill_loss(output, target, teacher_output, loss_fn=distillation, opt=optimizer):
    loss_b = loss_fn(output, target, teacher_output, alpha=0.1, T=10)

    if opt is not None:
        opt.zero_grad()
        loss_b.backward()
        opt.step()

    return loss_b.item()

In [532]:
def student_train(s_model, t_model, optimizer, train_loader, val_loader, scheduler, device):
    s_model.to(device)
    t_model.to(device)
    
    best_score = 0
    best_model = None

    for epoch in range(CFG["EPOCHS"]):
        train_loss = []
        s_model.train()
        t_model.eval()    # teather는 이번에는 학습하지 않으므로 .eval()로 불러온다
        
        for X_t, X_s, y in tqdm(train_loader):
            X_t = X_t.float().to(device)
            X_s = X_s.float().to(device)
            y = y.float().to(device)
            
            optimizer.zero_grad()

            output = s_model(X_s)
            with torch.no_grad():
                teacher_output = t_model(X_t)
                
            loss_b = distill_loss(output, y, teacher_output, loss_fn=distillation, opt=optimizer)

            train_loss.append(loss_b)

        val_loss, val_score = validation_student(s_model, t_model, val_loader, distill_loss, device)
        print(f'Epoch [{epoch}], Train Loss : [{np.mean(train_loss) :.5f}] Val Loss : [{np.mean(val_loss) :.5f}] Val F1 Score : [{val_score:.5f}]')
        
        if scheduler is not None:
            scheduler.step(val_score)
            
        if best_score < val_score:
            best_model = s_model
            best_score = val_score
    
    print(f"Student Train Best Score는 {best_score} 입니다.")
        
    return best_model

In [533]:
def validation_student(s_model, t_model, val_loader, criterion, device):
    s_model.eval()
    t_model.eval()

    val_loss = []
    pred_labels = []
    true_labels = []
    threshold = CFG['S_Thresh']
    
    with torch.no_grad():
        for X_t, X_s, y in tqdm(val_loader):
            X_t = X_t.float().to(device)
            X_s = X_s.float().to(device)
            y = y.float().to(device)
            
            model_pred = s_model(X_s)
            teacher_output = t_model(X_t)
            
            loss_b = distill_loss(model_pred, y, teacher_output, loss_fn=distillation, opt=None)
            val_loss.append(loss_b)
            
            model_pred = model_pred.squeeze(1).to('cpu')
            pred_labels += model_pred.tolist()
            true_labels += y.tolist()
        
        pred_labels = np.where(np.array(pred_labels) > threshold, 1, 0)
        val_f1 = competition_metric(true_labels, pred_labels)
        cf = confusion_matrix(true_labels, pred_labels)        
        print(cf)
        print(classification_report(true_labels, pred_labels, target_names=["0: 정상", "1: 이상"]))
        
    return val_loss, val_f1    

In [534]:
train_dataset = CustomDataset(train_X, train_y, True)
val_dataset = CustomDataset(val_X, val_y, True)

train_loader = DataLoader(train_dataset, batch_size = CFG['BATCH_SIZE'], shuffle=True)
val_loader = DataLoader(val_dataset, batch_size = CFG['BATCH_SIZE'], shuffle=False)

In [535]:
test_stage_features

Index(['encoder__x0_COMPONENT2', 'encoder__x0_COMPONENT3',
       'encoder__x0_COMPONENT4', 'encoder__x1_y2', 'encoder__x1_y3',
       'encoder__x1_y4', 'encoder__x1_y5', 'ANONYMOUS_1', 'ANONYMOUS_2', 'AG',
       'CO', 'CR', 'CU', 'FE', 'H2O', 'MN', 'MO', 'NI', 'PQINDEX', 'TI', 'V',
       'V40', 'ZN'],
      dtype='object')

In [536]:
student_model = Student()
student_model.eval()
optimizer = torch.optim.Adam(student_model.parameters(), lr=CFG['LEARNING_RATE'])
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=1, threshold_mode='abs',min_lr=1e-8, verbose=True)

best_student_model = student_train(student_model, teacher_model, optimizer, train_loader, val_loader, scheduler, device)


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2555   23]
 [ 237    4]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.99      0.95      2578
       1: 이상       0.15      0.02      0.03       241

    accuracy                           0.91      2819
   macro avg       0.53      0.50      0.49      2819
weighted avg       0.85      0.91      0.87      2819

Epoch [0], Train Loss : [7.84696] Val Loss : [6.68569] Val F1 Score : [0.49072]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2503   75]
 [ 222   19]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.97      0.94      2578
       1: 이상       0.20      0.08      0.11       241

    accuracy                           0.89      2819
   macro avg       0.56      0.52      0.53      2819
weighted avg       0.86      0.89      0.87      2819

Epoch [1], Train Loss : [7.04253] Val Loss : [6.67362] Val F1 Score : [0.52871]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2522   56]
 [ 231   10]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.15      0.04      0.07       241

    accuracy                           0.90      2819
   macro avg       0.53      0.51      0.51      2819
weighted avg       0.85      0.90      0.87      2819

Epoch [2], Train Loss : [6.96500] Val Loss : [6.78826] Val F1 Score : [0.50566]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2543   35]
 [ 230   11]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.99      0.95      2578
       1: 이상       0.24      0.05      0.08       241

    accuracy                           0.91      2819
   macro avg       0.58      0.52      0.51      2819
weighted avg       0.86      0.91      0.88      2819

Epoch [3], Train Loss : [6.94012] Val Loss : [6.71957] Val F1 Score : [0.51357]
Epoch 00004: reducing learning rate of group 0 to 5.0000e-03.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2531   47]
 [ 231   10]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.18      0.04      0.07       241

    accuracy                           0.90      2819
   macro avg       0.55      0.51      0.51      2819
weighted avg       0.85      0.90      0.87      2819

Epoch [4], Train Loss : [6.86373] Val Loss : [6.60779] Val F1 Score : [0.50753]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2489   89]
 [ 216   25]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.97      0.94      2578
       1: 이상       0.22      0.10      0.14       241

    accuracy                           0.89      2819
   macro avg       0.57      0.53      0.54      2819
weighted avg       0.86      0.89      0.87      2819

Epoch [5], Train Loss : [6.77136] Val Loss : [6.67255] Val F1 Score : [0.54156]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2503   75]
 [ 223   18]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.97      0.94      2578
       1: 이상       0.19      0.07      0.11       241

    accuracy                           0.89      2819
   macro avg       0.56      0.52      0.53      2819
weighted avg       0.86      0.89      0.87      2819

Epoch [6], Train Loss : [6.76230] Val Loss : [6.69221] Val F1 Score : [0.52580]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2542   36]
 [ 234    7]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.99      0.95      2578
       1: 이상       0.16      0.03      0.05       241

    accuracy                           0.90      2819
   macro avg       0.54      0.51      0.50      2819
weighted avg       0.85      0.90      0.87      2819

Epoch [7], Train Loss : [6.71373] Val Loss : [6.62253] Val F1 Score : [0.49943]
Epoch 00008: reducing learning rate of group 0 to 2.5000e-03.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2525   53]
 [ 228   13]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.20      0.05      0.08       241

    accuracy                           0.90      2819
   macro avg       0.56      0.52      0.52      2819
weighted avg       0.86      0.90      0.87      2819

Epoch [8], Train Loss : [6.67314] Val Loss : [6.65758] Val F1 Score : [0.51599]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2527   51]
 [ 231   10]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.16      0.04      0.07       241

    accuracy                           0.90      2819
   macro avg       0.54      0.51      0.51      2819
weighted avg       0.85      0.90      0.87      2819

Epoch [9], Train Loss : [6.65183] Val Loss : [6.69445] Val F1 Score : [0.50669]
Epoch 00010: reducing learning rate of group 0 to 1.2500e-03.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2509   69]
 [ 225   16]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.97      0.94      2578
       1: 이상       0.19      0.07      0.10       241

    accuracy                           0.90      2819
   macro avg       0.55      0.52      0.52      2819
weighted avg       0.86      0.90      0.87      2819

Epoch [10], Train Loss : [6.54466] Val Loss : [6.69274] Val F1 Score : [0.52141]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2519   59]
 [ 228   13]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.18      0.05      0.08       241

    accuracy                           0.90      2819
   macro avg       0.55      0.52      0.51      2819
weighted avg       0.85      0.90      0.87      2819

Epoch [11], Train Loss : [6.58174] Val Loss : [6.66820] Val F1 Score : [0.51459]
Epoch 00012: reducing learning rate of group 0 to 6.2500e-04.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2519   59]
 [ 221   20]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.25      0.08      0.12       241

    accuracy                           0.90      2819
   macro avg       0.59      0.53      0.54      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [12], Train Loss : [6.52041] Val Loss : [6.66687] Val F1 Score : [0.53617]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2510   68]
 [ 221   20]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.97      0.95      2578
       1: 이상       0.23      0.08      0.12       241

    accuracy                           0.90      2819
   macro avg       0.57      0.53      0.53      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [13], Train Loss : [6.48294] Val Loss : [6.68220] Val F1 Score : [0.53357]
Epoch 00014: reducing learning rate of group 0 to 3.1250e-04.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2519   59]
 [ 221   20]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.25      0.08      0.12       241

    accuracy                           0.90      2819
   macro avg       0.59      0.53      0.54      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [14], Train Loss : [6.43841] Val Loss : [6.67166] Val F1 Score : [0.53617]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2517   61]
 [ 221   20]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.25      0.08      0.12       241

    accuracy                           0.90      2819
   macro avg       0.58      0.53      0.54      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [15], Train Loss : [6.42671] Val Loss : [6.70763] Val F1 Score : [0.53559]
Epoch 00016: reducing learning rate of group 0 to 1.5625e-04.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2525   53]
 [ 223   18]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.25      0.07      0.12       241

    accuracy                           0.90      2819
   macro avg       0.59      0.53      0.53      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [16], Train Loss : [6.47261] Val Loss : [6.68899] Val F1 Score : [0.53178]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2513   65]
 [ 221   20]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.97      0.95      2578
       1: 이상       0.24      0.08      0.12       241

    accuracy                           0.90      2819
   macro avg       0.58      0.53      0.53      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [17], Train Loss : [6.40385] Val Loss : [6.69812] Val F1 Score : [0.53443]
Epoch 00018: reducing learning rate of group 0 to 7.8125e-05.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2508   70]
 [ 218   23]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.97      0.95      2578
       1: 이상       0.25      0.10      0.14       241

    accuracy                           0.90      2819
   macro avg       0.58      0.53      0.54      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [18], Train Loss : [6.48978] Val Loss : [6.71530] Val F1 Score : [0.54171]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2514   64]
 [ 220   21]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.25      0.09      0.13       241

    accuracy                           0.90      2819
   macro avg       0.58      0.53      0.54      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [19], Train Loss : [6.42788] Val Loss : [6.70989] Val F1 Score : [0.53769]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2522   56]
 [ 221   20]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.26      0.08      0.13       241

    accuracy                           0.90      2819
   macro avg       0.59      0.53      0.54      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [20], Train Loss : [6.44416] Val Loss : [6.68029] Val F1 Score : [0.53706]
Epoch 00021: reducing learning rate of group 0 to 3.9063e-05.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2521   57]
 [ 222   19]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.25      0.08      0.12       241

    accuracy                           0.90      2819
   macro avg       0.58      0.53      0.53      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [21], Train Loss : [6.45806] Val Loss : [6.67973] Val F1 Score : [0.53372]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2519   59]
 [ 220   21]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.26      0.09      0.13       241

    accuracy                           0.90      2819
   macro avg       0.59      0.53      0.54      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [22], Train Loss : [6.44141] Val Loss : [6.70156] Val F1 Score : [0.53918]
Epoch 00023: reducing learning rate of group 0 to 1.9531e-05.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2516   62]
 [ 219   22]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.26      0.09      0.14       241

    accuracy                           0.90      2819
   macro avg       0.59      0.53      0.54      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [23], Train Loss : [6.44139] Val Loss : [6.68595] Val F1 Score : [0.54125]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2513   65]
 [ 221   20]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.97      0.95      2578
       1: 이상       0.24      0.08      0.12       241

    accuracy                           0.90      2819
   macro avg       0.58      0.53      0.53      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [24], Train Loss : [6.48443] Val Loss : [6.69843] Val F1 Score : [0.53443]
Epoch 00025: reducing learning rate of group 0 to 9.7656e-06.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2513   65]
 [ 220   21]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.97      0.95      2578
       1: 이상       0.24      0.09      0.13       241

    accuracy                           0.90      2819
   macro avg       0.58      0.53      0.54      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [25], Train Loss : [6.47904] Val Loss : [6.70346] Val F1 Score : [0.53739]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2520   58]
 [ 222   19]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.25      0.08      0.12       241

    accuracy                           0.90      2819
   macro avg       0.58      0.53      0.53      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [26], Train Loss : [6.40817] Val Loss : [6.69125] Val F1 Score : [0.53343]
Epoch 00027: reducing learning rate of group 0 to 4.8828e-06.


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2509   69]
 [ 221   20]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.97      0.95      2578
       1: 이상       0.22      0.08      0.12       241

    accuracy                           0.90      2819
   macro avg       0.57      0.53      0.53      2819
weighted avg       0.86      0.90      0.87      2819

Epoch [27], Train Loss : [6.41393] Val Loss : [6.69635] Val F1 Score : [0.53329]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2509   69]
 [ 217   24]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.97      0.95      2578
       1: 이상       0.26      0.10      0.14       241

    accuracy                           0.90      2819
   macro avg       0.59      0.54      0.54      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [28], Train Loss : [6.40597] Val Loss : [6.71233] Val F1 Score : [0.54490]


  0%|          | 0/45 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

[[2518   60]
 [ 221   20]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.98      0.95      2578
       1: 이상       0.25      0.08      0.12       241

    accuracy                           0.90      2819
   macro avg       0.58      0.53      0.54      2819
weighted avg       0.86      0.90      0.88      2819

Epoch [29], Train Loss : [6.44263] Val Loss : [6.70763] Val F1 Score : [0.53588]
Student Train Best Score는 0.5448955031114242 입니다.


In [537]:
PATH1 = f"./models/{file_version}_student_net.pth"
torch.save(best_student_model.state_dict(), PATH1)

In [538]:
best_student_model = Student()
best_student_model.load_state_dict(torch.load(PATH1))
best_student_model

Student(
  (classifier): Sequential(
    (0): Linear(in_features=23, out_features=128, bias=True)
    (1): Dropout(p=0.2, inplace=False)
    (2): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): LeakyReLU(negative_slope=0.01)
    (4): Linear(in_features=128, out_features=512, bias=True)
    (5): Dropout(p=0.2, inplace=False)
    (6): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): LeakyReLU(negative_slope=0.01)
    (8): Linear(in_features=512, out_features=128, bias=True)
    (9): Dropout(p=0.2, inplace=False)
    (10): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (11): LeakyReLU(negative_slope=0.01)
    (12): Linear(in_features=128, out_features=1, bias=True)
    (13): Sigmoid()
  )
)

In [539]:
def choose_threshold(model, val_loader, device):
    model.to(device)
    model.eval()
    
#     thresholds = [0.1, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
    thresholds = [0.05, 0.1, 0.15, 0.2, 0.25, 0.3]

    pred_labels = []
    true_labels = []
    
    best_score = 0
    best_thr = None
    with torch.no_grad():
        for _, x_s, y in tqdm(iter(val_loader)):
            x_s = x_s.float().to(device)
            y = y.float().to(device)
            
            model_pred = model(x_s)
            
            model_pred = model_pred.squeeze(1).to('cpu')
            pred_labels += model_pred.tolist()
            true_labels += y.tolist()
        
        for threshold in thresholds:
            pred_labels_thr = np.where(np.array(pred_labels) > threshold, 1, 0)
            score_thr = competition_metric(true_labels, pred_labels_thr)
            cf1 = confusion_matrix(true_labels, pred_labels_thr)  

            print(cf1)
            print(classification_report(true_labels, pred_labels_thr, target_names=["0: 정상", "1: 이상"]))

            if best_score < score_thr:
                best_score = score_thr
                best_thr = threshold
                
    return best_thr, best_score

In [540]:
choose_threshold(best_student_model, val_loader, device)
best_threshold, best_score = choose_threshold(best_student_model, val_loader, device)
choose_threshold_result = f'Best Threshold : [{best_threshold}], Score : [{best_score:.5f}]'
print(choose_threshold_result)

  0%|          | 0/12 [00:00<?, ?it/s]

[[1087 1491]
 [  53  188]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.42      0.58      2578
       1: 이상       0.11      0.78      0.20       241

    accuracy                           0.45      2819
   macro avg       0.53      0.60      0.39      2819
weighted avg       0.88      0.45      0.55      2819

[[1693  885]
 [  94  147]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.66      0.78      2578
       1: 이상       0.14      0.61      0.23       241

    accuracy                           0.65      2819
   macro avg       0.54      0.63      0.50      2819
weighted avg       0.88      0.65      0.73      2819

[[2068  510]
 [ 140  101]]
              precision    recall  f1-score   support

       0: 정상       0.94      0.80      0.86      2578
       1: 이상       0.17      0.42      0.24       241

    accuracy                           0.77      2819
   macro avg       0.55      0.61      0.55    

  0%|          | 0/12 [00:00<?, ?it/s]

[[1087 1491]
 [  53  188]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.42      0.58      2578
       1: 이상       0.11      0.78      0.20       241

    accuracy                           0.45      2819
   macro avg       0.53      0.60      0.39      2819
weighted avg       0.88      0.45      0.55      2819

[[1693  885]
 [  94  147]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.66      0.78      2578
       1: 이상       0.14      0.61      0.23       241

    accuracy                           0.65      2819
   macro avg       0.54      0.63      0.50      2819
weighted avg       0.88      0.65      0.73      2819

[[2068  510]
 [ 140  101]]
              precision    recall  f1-score   support

       0: 정상       0.94      0.80      0.86      2578
       1: 이상       0.17      0.42      0.24       241

    accuracy                           0.77      2819
   macro avg       0.55      0.61      0.55    

In [541]:
test_datasets = CustomDataset(test, None, False)
test_loaders = DataLoader(test_datasets, batch_size = CFG['BATCH_SIZE'], shuffle=False)

In [542]:
def inference(model, test_loader, threshold, device):
    model.to(device)
    model.eval()
    # .eval함수는 evaluation 과정에서 사용하지 말아야 하는 layer들을 알아서 off 시키는 함수
    
    test_predict = []
    with torch.no_grad():
        for x in tqdm(test_loader):
            x = x.float().to(device)
            model_pred = model(x)

            model_pred = model_pred.squeeze(1).to('cpu')
            test_predict += model_pred
        
    test_predict = np.where(np.array(test_predict) > threshold, 1, 0)  
    # threshhold 보다 큰 값을 찾아서 1로 바꾸고, 아닌 것은 0으로 변경해라
    print('Done.')
    return test_predict

In [543]:
preds = inference(best_student_model, test_loaders, best_threshold, device)

  0%|          | 0/24 [00:00<?, ?it/s]

Done.


In [544]:
submit = pd.read_csv('./data/sample_submission.csv')
submit['Y_LABEL'] = preds
submit.head()

ID  Y_LABEL
0  TEST_0000        0
1  TEST_0001        0
2  TEST_0002        0
3  TEST_0003        0
4  TEST_0004        0

In [545]:
pred_cnt = tuple(submit["Y_LABEL"].value_counts())
a, b = pred_cnt
r = f"정상값 개수 : {a}, 이상값 개수 : {b}"
print(r)

정상값 개수 : 5597, 이상값 개수 : 444


In [546]:
submit.to_csv(f'./submits/submit{file_version}.csv', index=False)

In [547]:
record = {"ver": file_version, "CFG": CFG, "Val_result": choose_threshold_result, "pred_cnt": r}
record

{'ver': 33,
 'CFG': {'EPOCHS': 30,
  'LEARNING_RATE': 0.01,
  'BATCH_SIZE': 256,
  'SEED': 43,
  'log_transform_turn': 1,
  'skew_cut': 0.01,
  'vif_cut': 10,
  'corr_cut': 0.0075,
  'outlier_corr_cut': 100,
  'T_Thresh': 0.3,
  'S_Thresh': 0.325,
  'reduct': 'sum',
  'drop_rate': 0.2},
 'Val_result': 'Best Threshold : [0.25], Score : [0.57635]',
 'pred_cnt': '정상값 개수 : 5597, 이상값 개수 : 444'}