In [929]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset

from sklearn.metrics import f1_score, confusion_matrix, classification_report
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold, StratifiedKFold

import os
import pandas as pd
import numpy as np
from tqdm.auto import tqdm
import random
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings(action='ignore') 

device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

In [930]:
file_version = 54
CFG = {
    'EPOCHS': 30,
    'LEARNING_RATE':1e-2,    # 0.01
    'BATCH_SIZE':256,  #256
    'SEED':43,
    'log_transform_turn': 1,  # 로그 트랜스폼을 몇번 돌릴 것인가?
    'skew_cut':0.01,           # 왜도 얼마 이상을 로그값으로 정규화할 것인가?(100이면 안하겠다는 것)
    'vif_cut': 10,           # 다중공선성 vif 얼마 이상을 제거할 것인가?
    'corr_cut': 0.004,     # 일정 상관관계 이하 칼럼은 드랍
    'outlier_corr_cut': 100,    # 이값 이상의 상관관계를 갖는 칼럼에 대해서만 아웃라이어 제거(100이면 미적용)
    'T_Thresh': 0.3,     # Teacher model train Threshhold 최초 0.35
    'S_Thresh': 0.325,     # Student model train Threshold 최초 0.35
    'reduct' : 'sum',      # sum, mean
    'drop_rate': 0.2,
    
}

In [931]:
import pickle
#불러오기

with open(f"./data/{file_version}_1_train_X", 'rb') as pickle_filename:
    train_X_1 = pickle.load(pickle_filename)
with open(f"./data/{file_version}_1_train_y", 'rb') as pickle_filename:
    train_y_1 = pickle.load(pickle_filename)
with open(f"./data/{file_version}_1_val_X", 'rb') as pickle_filename:
    val_X_1 = pickle.load(pickle_filename)
with open(f"./data/{file_version}_1_val_y", 'rb') as pickle_filename:
    val_y_1 = pickle.load(pickle_filename)     
with open(f"./data/{file_version}_1_test", 'rb') as pickle_filename:
    test_1 = pickle.load(pickle_filename)

with open(f"./data/{file_version}_2_train_X", 'rb') as pickle_filename:
    train_X_2 = pickle.load(pickle_filename)
with open(f"./data/{file_version}_2_train_y", 'rb') as pickle_filename:
    train_y_2 = pickle.load(pickle_filename)
with open(f"./data/{file_version}_2_val_X", 'rb') as pickle_filename:
    val_X_2 = pickle.load(pickle_filename)
with open(f"./data/{file_version}_2_val_y", 'rb') as pickle_filename:
    val_y_2 = pickle.load(pickle_filename)     
with open(f"./data/{file_version}_2_test", 'rb') as pickle_filename:
    test_2 = pickle.load(pickle_filename)

with open(f"./data/{file_version}_3_train_X", 'rb') as pickle_filename:
    train_X_3 = pickle.load(pickle_filename)
with open(f"./data/{file_version}_3_train_y", 'rb') as pickle_filename:
    train_y_3 = pickle.load(pickle_filename)
with open(f"./data/{file_version}_3_val_X", 'rb') as pickle_filename:
    val_X_3 = pickle.load(pickle_filename)
with open(f"./data/{file_version}_3_val_y", 'rb') as pickle_filename:
    val_y_3 = pickle.load(pickle_filename)     
with open(f"./data/{file_version}_3_test", 'rb') as pickle_filename:
    test_3 = pickle.load(pickle_filename)
    
with open(f"./data/{file_version}_4_train_X", 'rb') as pickle_filename:
    train_X_4 = pickle.load(pickle_filename)
with open(f"./data/{file_version}_4_train_y", 'rb') as pickle_filename:
    train_y_4 = pickle.load(pickle_filename)
with open(f"./data/{file_version}_4_val_X", 'rb') as pickle_filename:
    val_X_4 = pickle.load(pickle_filename)
with open(f"./data/{file_version}_4_val_y", 'rb') as pickle_filename:
    val_y_4 = pickle.load(pickle_filename)     
with open(f"./data/{file_version}_4_test", 'rb') as pickle_filename:
    test_4 = pickle.load(pickle_filename)

FileNotFoundError: [Errno 2] No such file or directory: './data/53_1_train_X'

In [ ]:
train_X_list = [train_X_1, train_X_2, train_X_3, train_X_4]
train_y_list = [train_y_1, train_y_2, train_y_3, train_y_4]
val_X_list = [val_X_1, val_X_2, val_X_3, val_X_4]
val_y_list = [val_y_1, val_y_2, val_y_3, val_y_4]
test_list = [test_1, test_2, test_3, test_4]

In [ ]:
train_X_1.shape, train_y_1.shape, val_X_1.shape, val_y_1.shape

In [ ]:
# test_1.iloc[:,:-1]

In [ ]:
class CustomDataset(Dataset):
    def __init__(self, data_X, data_y, distillation=False):
        super(CustomDataset, self).__init__()
        self.data_X = data_X
        self.data_y = data_y
        self.distillation = distillation
        
    def __len__(self):
        return len(self.data_X)
    
    def __getitem__(self, index):
        if self.distillation:
            # 지식 증류 학습 시
            teacher_X = torch.Tensor(self.data_X.iloc[index])
            student_X = torch.Tensor(self.data_X[test_stage_features].iloc[index])
            y = self.data_y.values[index]
            return teacher_X, student_X, y
        else:
            if self.data_y is None:
                test_X = torch.Tensor(self.data_X.iloc[index])
                return test_X
            else:
                teacher_X = torch.Tensor(self.data_X.iloc[index])

                y = self.data_y.values[index]
                return teacher_X, y

In [ ]:
train_loaders = []
val_loaders = []

for a, b, c, d, e in zip(train_X_list, train_y_list, val_X_list, val_y_list, test_list):
    
    test_stage_features = e.iloc[:,:-1].columns
    
    train_dataset = CustomDataset(a, b, False)
    val_dataset = CustomDataset(c, d, False)
    
    train_loader = DataLoader(train_dataset, batch_size = CFG['BATCH_SIZE'], shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size = CFG['BATCH_SIZE'], shuffle=False)
    
#     print(train_loader)
#     print(list(train_loader))
    
    train_loaders.append(train_loader)
    val_loaders.append(val_loader)


In [ ]:
class Teacher(nn.Module):
    def __init__(self):
        super(Teacher, self).__init__()
        self.classifier = nn.Sequential(
            nn.Linear(in_features=train_col_num, out_features=256),
            nn.Dropout(p=CFG['drop_rate']),
            nn.BatchNorm1d(256),
            nn.LeakyReLU(),
            nn.Linear(in_features=256, out_features=1024),
            nn.Dropout(p=CFG['drop_rate']),
            nn.BatchNorm1d(1024),
            nn.LeakyReLU(),
            nn.Linear(in_features=1024, out_features=256),
            nn.Dropout(p=CFG['drop_rate']),
            nn.BatchNorm1d(256),
            nn.LeakyReLU(),
            nn.Linear(in_features=256, out_features=1),
            nn.Sigmoid()
        )
        
    def forward(self, x):
        output = self.classifier(x)
        return output

In [ ]:
def train(model, optimizer, train_loader, val_loader, scheduler, device):
    model.to(device)

    best_score = 0
    best_model = None
    
    # Loss Function 정의
    criterion = nn.BCELoss(reduction = CFG['reduct']).to(device)  #BCEWithLogitsLoss
#     criterion = nn.BCEWithLogitsLoss(reduction = CFG['reduct']).to(device)  #BCEWithLogitsLoss

    for epoch in range(CFG["EPOCHS"]):
        train_loss = []
  
        model.train()
        for X, y in tqdm(train_loader):
            X = X.float().to(device)
            y = y.float().to(device)
            
            optimizer.zero_grad()
            
            y_pred = model(X)
            
            loss = criterion(y_pred, y.reshape(-1, 1))  # loss_fn(input, target)
            loss.backward()
            
            optimizer.step()

            train_loss.append(loss.item())

        val_loss, val_score = validation_teacher(model, val_loader, criterion, device)
        print(f'Epoch [{epoch}], Train Loss : [{np.mean(train_loss) :.5f}] Val Loss : [{np.mean(val_loss) :.5f}] Val F1 Score : [{val_score:.5f}]')

        if scheduler is not None:
            scheduler.step(val_score)
            
        if best_score < val_score:
            best_model = model
            best_score = val_score
    print(f"Teacher Train Best Score는 {best_score} 입니다.")
    return best_model 

In [ ]:
def competition_metric(true, pred):
    return f1_score(true, pred, average="macro")


def validation_teacher(model, val_loader, criterion, device):
    model.eval()

    val_loss = []
    pred_labels = []
    true_labels = []
    threshold = CFG['T_Thresh']     
    
    with torch.no_grad():
        for X, y in tqdm(val_loader):
            X = X.float().to(device)
            y = y.float().to(device)
            
            model_pred = model(X.to(device))
            
            loss = criterion(model_pred, y.reshape(-1, 1))
            val_loss.append(loss.item())      
            
            model_pred = model_pred.squeeze(1).to('cpu')  # squeeze함수는 차원이 1인 차원을 제거해준다.
            pred_labels += model_pred.tolist()
            true_labels += y.tolist()
        
        #print(pred_labels[0:10])
        # 오일상태는 0: 정상, 1: 이상
        # 어느 임계점 thrshold보다 큰 예측 라벨을 1로 하고, 나머지를 0으로 할 것인가?
        pred_labels = np.where(np.array(pred_labels) > threshold, 1, 0)
        #print(pred_labels[0:10])
        cf = confusion_matrix(true_labels, pred_labels)
        val_f1 = competition_metric(true_labels, pred_labels)
        
        print(cf)
        print(classification_report(true_labels, pred_labels, target_names=["0: 정상", "1: 이상"]))
    return val_loss, val_f1

In [ ]:
teachers = []

for a, b, c, d in zip(train_loaders, val_loaders, train_X_list, test_list):
    train_col_num = len(c.columns)
    test_stage_features = d.iloc[:,:-1].columns
    test_col_num = len(d.columns)
    
    print("***")
    
    model = Teacher()
    model.eval()
    optimizer = torch.optim.Adam(model.parameters(), lr=CFG['LEARNING_RATE'])
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=1, threshold_mode='abs',min_lr=1e-8, verbose=True)
    pred_labels = []
    true_labels = []

    teacher_model = train(model, optimizer, a, b, scheduler, device)
    teachers.append(teacher_model)
    
    print("부분학습 종료")
    
    
print("전체 학습 종료")

In [ ]:
for i, teacher in enumerate(teachers):
    PATH1 = f"./models/{file_version}_{i}_teacher_net.pth"
    torch.save(teacher.state_dict(), PATH1)

In [ ]:
class Student(nn.Module):
    def __init__(self):
        super(Student, self).__init__()
        self.classifier = nn.Sequential(
            nn.Linear(in_features=test_col_num, out_features=128),
            nn.Dropout(p=CFG['drop_rate']),
            nn.BatchNorm1d(128),
            nn.LeakyReLU(),
            nn.Linear(in_features=128, out_features=512),
            nn.Dropout(p=CFG['drop_rate']),
            nn.BatchNorm1d(512),
            nn.LeakyReLU(),
            nn.Linear(in_features=512, out_features=128),
            nn.Dropout(p=CFG['drop_rate']),
            nn.BatchNorm1d(128),
            nn.LeakyReLU(),
            nn.Linear(in_features=128, out_features=1),
            nn.Sigmoid()
        )
        
    def forward(self, x):
        output = self.classifier(x)
        return output

In [938]:
# distillation Function 정의

# def distillation(student_logits, labels, teacher_logits, alpha, T):
def distillation(student_logits, labels, teacher_logits, alpha):

    student_loss = nn.BCELoss(reduction = CFG['reduct'])(student_logits, labels.reshape(-1, 1)) #BCEWithLogitsLoss
#     student_loss = nn.BCEWithLogitsLoss(reduction = CFG['reduct'])(student_logits, labels.reshape(-1, 1)) #BCEWithLogitsLoss
    
    distillation_loss = nn.BCELoss()(student_logits, teacher_logits)
#     distillation_loss = nn.KLDivLoss(reduction='batchmean')(F.log_softmax(student_logits/T, dim=1), F.softmax(teacher_logits/T, dim=1)) * (T * T)
    
    return alpha * student_loss + (1-alpha) * distillation_loss

def distill_loss(output, target, teacher_output, loss_fn=distillation, opt=optimizer):
#     loss_b = loss_fn(output, target, teacher_output, alpha=0.1, T=10)
    loss_b = loss_fn(output, target, teacher_output, alpha=0.1)

    if opt is not None:
        opt.zero_grad()
        loss_b.backward()
        opt.step()

    return loss_b.item()

In [939]:
def student_train(s_model, t_model, optimizer, train_loader, val_loader, scheduler, device):
    s_model.to(device)
    t_model.to(device)
    
    best_score = 0
    best_model = None

    for epoch in range(CFG["EPOCHS"]):
        train_loss = []
        s_model.train()
        t_model.eval()    # teather는 이번에는 학습하지 않으므로 .eval()로 불러온다
        
        for X_t, X_s, y in tqdm(train_loader):
            X_t = X_t.float().to(device)
            X_s = X_s.float().to(device)
            y = y.float().to(device)
            
            optimizer.zero_grad()

            output = s_model(X_s)
            with torch.no_grad():
                teacher_output = t_model(X_t)
                
            loss_b = distill_loss(output, y, teacher_output, loss_fn=distillation, opt=optimizer)

            train_loss.append(loss_b)

        val_loss, val_score = validation_student(s_model, t_model, val_loader, distill_loss, device)
        print(f'Epoch [{epoch}], Train Loss : [{np.mean(train_loss) :.5f}] Val Loss : [{np.mean(val_loss) :.5f}] Val F1 Score : [{val_score:.5f}]')
        
        if scheduler is not None:
            scheduler.step(val_score)
            
        if best_score < val_score:
            best_model = s_model
            best_score = val_score
    
    print(f"Student Train Best Score는 {best_score} 입니다.")
        
    return best_model

In [940]:
def validation_student(s_model, t_model, val_loader, criterion, device):
    s_model.eval()
    t_model.eval()

    val_loss = []
    pred_labels = []
    true_labels = []
    threshold = CFG['S_Thresh']
    
    with torch.no_grad():
        for X_t, X_s, y in tqdm(val_loader):
            X_t = X_t.float().to(device)
            X_s = X_s.float().to(device)
            y = y.float().to(device)
            
            model_pred = s_model(X_s)
            teacher_output = t_model(X_t)
            
            loss_b = distill_loss(model_pred, y, teacher_output, loss_fn=distillation, opt=None)
            val_loss.append(loss_b)
            
            model_pred = model_pred.squeeze(1).to('cpu')
            pred_labels += model_pred.tolist()
            true_labels += y.tolist()
        
        pred_labels = np.where(np.array(pred_labels) > threshold, 1, 0)
        val_f1 = competition_metric(true_labels, pred_labels)
        cf = confusion_matrix(true_labels, pred_labels)        
        print(cf)
        print(classification_report(true_labels, pred_labels, target_names=["0: 정상", "1: 이상"]))
        
    return val_loss, val_f1    

In [941]:
s_train_loaders = []
s_val_loaders = []

for a, b, c, d, e in zip(train_X_list, train_y_list, val_X_list, val_y_list, test_list):
    
    test_stage_features = e.iloc[:,:-1].columns
    
    train_dataset = CustomDataset(a, b, True)
    val_dataset = CustomDataset(c, d, True)
    
    train_loader = DataLoader(train_dataset, batch_size = CFG['BATCH_SIZE'], shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size = CFG['BATCH_SIZE'], shuffle=False)
    
#     print(train_loader)
#     print(list(train_loader))
    
    s_train_loaders.append(train_loader)
    s_val_loaders.append(val_loader)


In [942]:
students = []

for a, b, c, d, e in zip(s_train_loaders, s_val_loaders, train_X_list, test_list, teachers):
    train_col_num = len(c.columns)
    test_stage_features = d.iloc[:,:-1].columns
#     print(test_stage_features)
    test_col_num = len(test_stage_features)

    student_model = Student()
    student_model.eval()
    optimizer = torch.optim.Adam(student_model.parameters(), lr=CFG['LEARNING_RATE'])
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=1, threshold_mode='abs',min_lr=1e-8, verbose=True)

    best_student_model = student_train(student_model, e, optimizer, a, b, scheduler, device)

    students.append(best_student_model)
    
    print("부분학습 종료")

print("전체 학습 종료")
    
# print(students)

  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[653  63]
 [ 51  11]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.91      0.92       716
       1: 이상       0.15      0.18      0.16        62

    accuracy                           0.85       778
   macro avg       0.54      0.54      0.54       778
weighted avg       0.87      0.85      0.86       778

Epoch [0], Train Loss : [9.26073] Val Loss : [6.28388] Val F1 Score : [0.54074]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[599 117]
 [ 43  19]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.84      0.88       716
       1: 이상       0.14      0.31      0.19        62

    accuracy                           0.79       778
   macro avg       0.54      0.57      0.54       778
weighted avg       0.87      0.79      0.83       778

Epoch [1], Train Loss : [7.03595] Val Loss : [6.55925] Val F1 Score : [0.53705]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[692  24]
 [ 55   7]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.97      0.95       716
       1: 이상       0.23      0.11      0.15        62

    accuracy                           0.90       778
   macro avg       0.58      0.54      0.55       778
weighted avg       0.87      0.90      0.88       778

Epoch [2], Train Loss : [6.43197] Val Loss : [5.77777] Val F1 Score : [0.54827]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[661  55]
 [ 52  10]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.92      0.93       716
       1: 이상       0.15      0.16      0.16        62

    accuracy                           0.86       778
   macro avg       0.54      0.54      0.54       778
weighted avg       0.87      0.86      0.86       778

Epoch [3], Train Loss : [6.07848] Val Loss : [6.05607] Val F1 Score : [0.54130]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[677  39]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.95      0.94       716
       1: 이상       0.19      0.15      0.16        62

    accuracy                           0.88       778
   macro avg       0.56      0.55      0.55       778
weighted avg       0.87      0.88      0.87       778

Epoch [4], Train Loss : [6.04638] Val Loss : [5.97990] Val F1 Score : [0.55001]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[679  37]
 [ 55   7]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.95      0.94       716
       1: 이상       0.16      0.11      0.13        62

    accuracy                           0.88       778
   macro avg       0.54      0.53      0.53       778
weighted avg       0.86      0.88      0.87       778

Epoch [5], Train Loss : [5.86318] Val Loss : [6.11696] Val F1 Score : [0.53431]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[663  53]
 [ 52  10]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93       716
       1: 이상       0.16      0.16      0.16        62

    accuracy                           0.87       778
   macro avg       0.54      0.54      0.54       778
weighted avg       0.87      0.87      0.87       778

Epoch [6], Train Loss : [5.73010] Val Loss : [6.39017] Val F1 Score : [0.54331]
Epoch 00007: reducing learning rate of group 0 to 5.0000e-03.


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[678  38]
 [ 57   5]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.95      0.93       716
       1: 이상       0.12      0.08      0.10        62

    accuracy                           0.88       778
   macro avg       0.52      0.51      0.51       778
weighted avg       0.86      0.88      0.87       778

Epoch [7], Train Loss : [5.53677] Val Loss : [6.29874] Val F1 Score : [0.51488]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[675  41]
 [ 55   7]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.94      0.93       716
       1: 이상       0.15      0.11      0.13        62

    accuracy                           0.88       778
   macro avg       0.54      0.53      0.53       778
weighted avg       0.86      0.88      0.87       778

Epoch [8], Train Loss : [5.37042] Val Loss : [6.39044] Val F1 Score : [0.53044]
Epoch 00009: reducing learning rate of group 0 to 2.5000e-03.


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[680  36]
 [ 55   7]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.95      0.94       716
       1: 이상       0.16      0.11      0.13        62

    accuracy                           0.88       778
   macro avg       0.54      0.53      0.54       778
weighted avg       0.86      0.88      0.87       778

Epoch [9], Train Loss : [5.24564] Val Loss : [6.32694] Val F1 Score : [0.53531]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[675  41]
 [ 55   7]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.94      0.93       716
       1: 이상       0.15      0.11      0.13        62

    accuracy                           0.88       778
   macro avg       0.54      0.53      0.53       778
weighted avg       0.86      0.88      0.87       778

Epoch [10], Train Loss : [5.02855] Val Loss : [6.48258] Val F1 Score : [0.53044]
Epoch 00011: reducing learning rate of group 0 to 1.2500e-03.


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[670  46]
 [ 54   8]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.94      0.93       716
       1: 이상       0.15      0.13      0.14        62

    accuracy                           0.87       778
   macro avg       0.54      0.53      0.53       778
weighted avg       0.86      0.87      0.87       778

Epoch [11], Train Loss : [4.88741] Val Loss : [6.50769] Val F1 Score : [0.53424]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[671  45]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.94      0.93       716
       1: 이상       0.17      0.15      0.16        62

    accuracy                           0.87       778
   macro avg       0.55      0.54      0.54       778
weighted avg       0.87      0.87      0.87       778

Epoch [12], Train Loss : [4.91885] Val Loss : [6.49265] Val F1 Score : [0.54356]
Epoch 00013: reducing learning rate of group 0 to 6.2500e-04.


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[666  50]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93       716
       1: 이상       0.15      0.15      0.15        62

    accuracy                           0.87       778
   macro avg       0.54      0.54      0.54       778
weighted avg       0.86      0.87      0.87       778

Epoch [13], Train Loss : [4.90934] Val Loss : [6.49167] Val F1 Score : [0.53849]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[667  49]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93       716
       1: 이상       0.16      0.15      0.15        62

    accuracy                           0.87       778
   macro avg       0.54      0.54      0.54       778
weighted avg       0.86      0.87      0.87       778

Epoch [14], Train Loss : [4.87833] Val Loss : [6.49837] Val F1 Score : [0.53948]
Epoch 00015: reducing learning rate of group 0 to 3.1250e-04.


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[665  51]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93       716
       1: 이상       0.15      0.15      0.15        62

    accuracy                           0.87       778
   macro avg       0.54      0.54      0.54       778
weighted avg       0.86      0.87      0.87       778

Epoch [15], Train Loss : [4.72022] Val Loss : [6.55146] Val F1 Score : [0.53751]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[664  52]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93       716
       1: 이상       0.15      0.15      0.15        62

    accuracy                           0.87       778
   macro avg       0.54      0.54      0.54       778
weighted avg       0.86      0.87      0.86       778

Epoch [16], Train Loss : [4.75230] Val Loss : [6.55720] Val F1 Score : [0.53653]
Epoch 00017: reducing learning rate of group 0 to 1.5625e-04.


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[666  50]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93       716
       1: 이상       0.15      0.15      0.15        62

    accuracy                           0.87       778
   macro avg       0.54      0.54      0.54       778
weighted avg       0.86      0.87      0.87       778

Epoch [17], Train Loss : [4.68142] Val Loss : [6.52740] Val F1 Score : [0.53849]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[665  51]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93       716
       1: 이상       0.15      0.15      0.15        62

    accuracy                           0.87       778
   macro avg       0.54      0.54      0.54       778
weighted avg       0.86      0.87      0.87       778

Epoch [18], Train Loss : [4.78561] Val Loss : [6.53291] Val F1 Score : [0.53751]
Epoch 00019: reducing learning rate of group 0 to 7.8125e-05.


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[670  46]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.94      0.93       716
       1: 이상       0.16      0.15      0.15        62

    accuracy                           0.87       778
   macro avg       0.55      0.54      0.54       778
weighted avg       0.87      0.87      0.87       778

Epoch [19], Train Loss : [4.66543] Val Loss : [6.52283] Val F1 Score : [0.54252]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[661  55]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.92      0.92       716
       1: 이상       0.14      0.15      0.14        62

    accuracy                           0.86       778
   macro avg       0.53      0.53      0.53       778
weighted avg       0.86      0.86      0.86       778

Epoch [20], Train Loss : [4.69104] Val Loss : [6.56667] Val F1 Score : [0.53367]
Epoch 00021: reducing learning rate of group 0 to 3.9063e-05.


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[663  53]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93       716
       1: 이상       0.15      0.15      0.15        62

    accuracy                           0.86       778
   macro avg       0.54      0.54      0.54       778
weighted avg       0.86      0.86      0.86       778

Epoch [21], Train Loss : [4.72749] Val Loss : [6.56020] Val F1 Score : [0.53557]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[662  54]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.92      0.93       716
       1: 이상       0.14      0.15      0.14        62

    accuracy                           0.86       778
   macro avg       0.53      0.53      0.53       778
weighted avg       0.86      0.86      0.86       778

Epoch [22], Train Loss : [4.55813] Val Loss : [6.58000] Val F1 Score : [0.53461]
Epoch 00023: reducing learning rate of group 0 to 1.9531e-05.


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[664  52]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93       716
       1: 이상       0.15      0.15      0.15        62

    accuracy                           0.87       778
   macro avg       0.54      0.54      0.54       778
weighted avg       0.86      0.87      0.86       778

Epoch [23], Train Loss : [4.66620] Val Loss : [6.57029] Val F1 Score : [0.53653]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[662  54]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.92      0.93       716
       1: 이상       0.14      0.15      0.14        62

    accuracy                           0.86       778
   macro avg       0.53      0.53      0.53       778
weighted avg       0.86      0.86      0.86       778

Epoch [24], Train Loss : [4.52573] Val Loss : [6.55774] Val F1 Score : [0.53461]
Epoch 00025: reducing learning rate of group 0 to 9.7656e-06.


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[665  51]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93       716
       1: 이상       0.15      0.15      0.15        62

    accuracy                           0.87       778
   macro avg       0.54      0.54      0.54       778
weighted avg       0.86      0.87      0.87       778

Epoch [25], Train Loss : [4.70290] Val Loss : [6.55591] Val F1 Score : [0.53751]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[659  57]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.92      0.92       716
       1: 이상       0.14      0.15      0.14        62

    accuracy                           0.86       778
   macro avg       0.53      0.53      0.53       778
weighted avg       0.86      0.86      0.86       778

Epoch [26], Train Loss : [4.61809] Val Loss : [6.59656] Val F1 Score : [0.53180]
Epoch 00027: reducing learning rate of group 0 to 4.8828e-06.


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[663  53]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93       716
       1: 이상       0.15      0.15      0.15        62

    accuracy                           0.86       778
   macro avg       0.54      0.54      0.54       778
weighted avg       0.86      0.86      0.86       778

Epoch [27], Train Loss : [4.66940] Val Loss : [6.57349] Val F1 Score : [0.53557]


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[661  55]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.92      0.92       716
       1: 이상       0.14      0.15      0.14        62

    accuracy                           0.86       778
   macro avg       0.53      0.53      0.53       778
weighted avg       0.86      0.86      0.86       778

Epoch [28], Train Loss : [4.67149] Val Loss : [6.60620] Val F1 Score : [0.53367]
Epoch 00029: reducing learning rate of group 0 to 2.4414e-06.


  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

[[662  54]
 [ 53   9]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.92      0.93       716
       1: 이상       0.14      0.15      0.14        62

    accuracy                           0.86       778
   macro avg       0.53      0.53      0.53       778
weighted avg       0.86      0.86      0.86       778

Epoch [29], Train Loss : [4.68638] Val Loss : [6.56858] Val F1 Score : [0.53461]
Student Train Best Score는 0.5500062869357475 입니다.
부분학습 종료


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[417   6]
 [ 41   0]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.99      0.95       423
       1: 이상       0.00      0.00      0.00        41

    accuracy                           0.90       464
   macro avg       0.46      0.49      0.47       464
weighted avg       0.83      0.90      0.86       464

Epoch [0], Train Loss : [9.56210] Val Loss : [7.83331] Val F1 Score : [0.47333]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[419   4]
 [ 41   0]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.99      0.95       423
       1: 이상       0.00      0.00      0.00        41

    accuracy                           0.90       464
   macro avg       0.46      0.50      0.47       464
weighted avg       0.83      0.90      0.87       464

Epoch [1], Train Loss : [7.99039] Val Loss : [7.75665] Val F1 Score : [0.47452]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[408  15]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.96      0.94       423
       1: 이상       0.17      0.07      0.10        41

    accuracy                           0.89       464
   macro avg       0.54      0.52      0.52       464
weighted avg       0.85      0.89      0.87       464

Epoch [2], Train Loss : [7.02063] Val Loss : [7.97448] Val F1 Score : [0.52035]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[411  12]
 [ 41   0]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.97      0.94       423
       1: 이상       0.00      0.00      0.00        41

    accuracy                           0.89       464
   macro avg       0.45      0.49      0.47       464
weighted avg       0.83      0.89      0.86       464

Epoch [3], Train Loss : [6.63590] Val Loss : [8.12063] Val F1 Score : [0.46971]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[422   1]
 [ 41   0]]
              precision    recall  f1-score   support

       0: 정상       0.91      1.00      0.95       423
       1: 이상       0.00      0.00      0.00        41

    accuracy                           0.91       464
   macro avg       0.46      0.50      0.48       464
weighted avg       0.83      0.91      0.87       464

Epoch [4], Train Loss : [6.28609] Val Loss : [8.33312] Val F1 Score : [0.47630]
Epoch 00005: reducing learning rate of group 0 to 5.0000e-03.


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[416   7]
 [ 41   0]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.98      0.95       423
       1: 이상       0.00      0.00      0.00        41

    accuracy                           0.90       464
   macro avg       0.46      0.49      0.47       464
weighted avg       0.83      0.90      0.86       464

Epoch [5], Train Loss : [6.12524] Val Loss : [8.23694] Val F1 Score : [0.47273]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[410  13]
 [ 41   0]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.97      0.94       423
       1: 이상       0.00      0.00      0.00        41

    accuracy                           0.88       464
   macro avg       0.45      0.48      0.47       464
weighted avg       0.83      0.88      0.86       464

Epoch [6], Train Loss : [5.91146] Val Loss : [8.42414] Val F1 Score : [0.46911]
Epoch 00007: reducing learning rate of group 0 to 2.5000e-03.


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[406  17]
 [ 40   1]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.96      0.93       423
       1: 이상       0.06      0.02      0.03        41

    accuracy                           0.88       464
   macro avg       0.48      0.49      0.48       464
weighted avg       0.83      0.88      0.85       464

Epoch [7], Train Loss : [5.86587] Val Loss : [8.38147] Val F1 Score : [0.48415]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[405  18]
 [ 39   2]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.96      0.93       423
       1: 이상       0.10      0.05      0.07        41

    accuracy                           0.88       464
   macro avg       0.51      0.50      0.50       464
weighted avg       0.84      0.88      0.86       464

Epoch [8], Train Loss : [5.66863] Val Loss : [8.33381] Val F1 Score : [0.49991]
Epoch 00009: reducing learning rate of group 0 to 1.2500e-03.


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[406  17]
 [ 39   2]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.96      0.94       423
       1: 이상       0.11      0.05      0.07        41

    accuracy                           0.88       464
   macro avg       0.51      0.50      0.50       464
weighted avg       0.84      0.88      0.86       464

Epoch [9], Train Loss : [5.67843] Val Loss : [8.40897] Val F1 Score : [0.50108]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[407  16]
 [ 39   2]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.96      0.94       423
       1: 이상       0.11      0.05      0.07        41

    accuracy                           0.88       464
   macro avg       0.51      0.51      0.50       464
weighted avg       0.84      0.88      0.86       464

Epoch [10], Train Loss : [5.42459] Val Loss : [8.41096] Val F1 Score : [0.50225]
Epoch 00011: reducing learning rate of group 0 to 6.2500e-04.


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[406  17]
 [ 39   2]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.96      0.94       423
       1: 이상       0.11      0.05      0.07        41

    accuracy                           0.88       464
   macro avg       0.51      0.50      0.50       464
weighted avg       0.84      0.88      0.86       464

Epoch [11], Train Loss : [5.51441] Val Loss : [8.44967] Val F1 Score : [0.50108]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[406  17]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.96      0.94       423
       1: 이상       0.15      0.07      0.10        41

    accuracy                           0.88       464
   macro avg       0.53      0.52      0.52       464
weighted avg       0.85      0.88      0.86       464

Epoch [12], Train Loss : [5.49103] Val Loss : [8.51329] Val F1 Score : [0.51746]
Epoch 00013: reducing learning rate of group 0 to 3.1250e-04.


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[403  20]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.95      0.93       423
       1: 이상       0.13      0.07      0.09        41

    accuracy                           0.88       464
   macro avg       0.52      0.51      0.51       464
weighted avg       0.84      0.88      0.86       464

Epoch [13], Train Loss : [5.51247] Val Loss : [8.52752] Val F1 Score : [0.51331]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[402  21]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.95      0.93       423
       1: 이상       0.12      0.07      0.09        41

    accuracy                           0.87       464
   macro avg       0.52      0.51      0.51       464
weighted avg       0.84      0.87      0.86       464

Epoch [14], Train Loss : [5.54014] Val Loss : [8.54035] Val F1 Score : [0.51197]
Epoch 00015: reducing learning rate of group 0 to 1.5625e-04.


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[402  21]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.95      0.93       423
       1: 이상       0.12      0.07      0.09        41

    accuracy                           0.87       464
   macro avg       0.52      0.51      0.51       464
weighted avg       0.84      0.87      0.86       464

Epoch [15], Train Loss : [5.51081] Val Loss : [8.56103] Val F1 Score : [0.51197]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[402  21]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.95      0.93       423
       1: 이상       0.12      0.07      0.09        41

    accuracy                           0.87       464
   macro avg       0.52      0.51      0.51       464
weighted avg       0.84      0.87      0.86       464

Epoch [16], Train Loss : [5.40408] Val Loss : [8.54688] Val F1 Score : [0.51197]
Epoch 00017: reducing learning rate of group 0 to 7.8125e-05.


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[401  22]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.95      0.93       423
       1: 이상       0.12      0.07      0.09        41

    accuracy                           0.87       464
   macro avg       0.52      0.51      0.51       464
weighted avg       0.84      0.87      0.86       464

Epoch [17], Train Loss : [5.49234] Val Loss : [8.55482] Val F1 Score : [0.51065]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[402  21]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.95      0.93       423
       1: 이상       0.12      0.07      0.09        41

    accuracy                           0.87       464
   macro avg       0.52      0.51      0.51       464
weighted avg       0.84      0.87      0.86       464

Epoch [18], Train Loss : [5.34977] Val Loss : [8.56639] Val F1 Score : [0.51197]
Epoch 00019: reducing learning rate of group 0 to 3.9063e-05.


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[401  22]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.95      0.93       423
       1: 이상       0.12      0.07      0.09        41

    accuracy                           0.87       464
   macro avg       0.52      0.51      0.51       464
weighted avg       0.84      0.87      0.86       464

Epoch [19], Train Loss : [5.48058] Val Loss : [8.57921] Val F1 Score : [0.51065]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[400  23]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.95      0.93       423
       1: 이상       0.12      0.07      0.09        41

    accuracy                           0.87       464
   macro avg       0.51      0.51      0.51       464
weighted avg       0.84      0.87      0.85       464

Epoch [20], Train Loss : [5.44900] Val Loss : [8.57462] Val F1 Score : [0.50935]
Epoch 00021: reducing learning rate of group 0 to 1.9531e-05.


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[401  22]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.95      0.93       423
       1: 이상       0.12      0.07      0.09        41

    accuracy                           0.87       464
   macro avg       0.52      0.51      0.51       464
weighted avg       0.84      0.87      0.86       464

Epoch [21], Train Loss : [5.47220] Val Loss : [8.56888] Val F1 Score : [0.51065]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[401  22]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.95      0.93       423
       1: 이상       0.12      0.07      0.09        41

    accuracy                           0.87       464
   macro avg       0.52      0.51      0.51       464
weighted avg       0.84      0.87      0.86       464

Epoch [22], Train Loss : [5.60742] Val Loss : [8.54874] Val F1 Score : [0.51065]
Epoch 00023: reducing learning rate of group 0 to 9.7656e-06.


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[402  21]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.95      0.93       423
       1: 이상       0.12      0.07      0.09        41

    accuracy                           0.87       464
   macro avg       0.52      0.51      0.51       464
weighted avg       0.84      0.87      0.86       464

Epoch [23], Train Loss : [5.47465] Val Loss : [8.55959] Val F1 Score : [0.51197]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[399  24]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.94      0.93       423
       1: 이상       0.11      0.07      0.09        41

    accuracy                           0.87       464
   macro avg       0.51      0.51      0.51       464
weighted avg       0.84      0.87      0.85       464

Epoch [24], Train Loss : [5.47801] Val Loss : [8.57498] Val F1 Score : [0.50807]
Epoch 00025: reducing learning rate of group 0 to 4.8828e-06.


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[398  25]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.94      0.93       423
       1: 이상       0.11      0.07      0.09        41

    accuracy                           0.86       464
   macro avg       0.51      0.51      0.51       464
weighted avg       0.84      0.86      0.85       464

Epoch [25], Train Loss : [5.34886] Val Loss : [8.53440] Val F1 Score : [0.50681]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[397  26]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.94      0.93       423
       1: 이상       0.10      0.07      0.09        41

    accuracy                           0.86       464
   macro avg       0.51      0.51      0.51       464
weighted avg       0.84      0.86      0.85       464

Epoch [26], Train Loss : [5.53238] Val Loss : [8.56793] Val F1 Score : [0.50556]
Epoch 00027: reducing learning rate of group 0 to 2.4414e-06.


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[399  24]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.94      0.93       423
       1: 이상       0.11      0.07      0.09        41

    accuracy                           0.87       464
   macro avg       0.51      0.51      0.51       464
weighted avg       0.84      0.87      0.85       464

Epoch [27], Train Loss : [5.41296] Val Loss : [8.57659] Val F1 Score : [0.50807]


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[399  24]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.94      0.93       423
       1: 이상       0.11      0.07      0.09        41

    accuracy                           0.87       464
   macro avg       0.51      0.51      0.51       464
weighted avg       0.84      0.87      0.85       464

Epoch [28], Train Loss : [5.44916] Val Loss : [8.56931] Val F1 Score : [0.50807]
Epoch 00029: reducing learning rate of group 0 to 1.2207e-06.


  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

[[399  24]
 [ 38   3]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.94      0.93       423
       1: 이상       0.11      0.07      0.09        41

    accuracy                           0.87       464
   macro avg       0.51      0.51      0.51       464
weighted avg       0.84      0.87      0.85       464

Epoch [29], Train Loss : [5.39818] Val Loss : [8.57081] Val F1 Score : [0.50807]
Student Train Best Score는 0.5203526359930565 입니다.
부분학습 종료


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1140  143]
 [ 106   21]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.89      0.90      1283
       1: 이상       0.13      0.17      0.14       127

    accuracy                           0.82      1410
   macro avg       0.52      0.53      0.52      1410
weighted avg       0.84      0.82      0.83      1410

Epoch [0], Train Loss : [9.57970] Val Loss : [8.29978] Val F1 Score : [0.52294]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1230   53]
 [ 114   13]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.96      0.94      1283
       1: 이상       0.20      0.10      0.13       127

    accuracy                           0.88      1410
   macro avg       0.56      0.53      0.54      1410
weighted avg       0.85      0.88      0.86      1410

Epoch [1], Train Loss : [7.40649] Val Loss : [7.38711] Val F1 Score : [0.53557]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1221   62]
 [ 111   16]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.95      0.93      1283
       1: 이상       0.21      0.13      0.16       127

    accuracy                           0.88      1410
   macro avg       0.56      0.54      0.54      1410
weighted avg       0.85      0.88      0.86      1410

Epoch [2], Train Loss : [7.09253] Val Loss : [7.48422] Val F1 Score : [0.54497]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1241   42]
 [ 114   13]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.97      0.94      1283
       1: 이상       0.24      0.10      0.14       127

    accuracy                           0.89      1410
   macro avg       0.58      0.53      0.54      1410
weighted avg       0.85      0.89      0.87      1410

Epoch [3], Train Loss : [6.88698] Val Loss : [7.23715] Val F1 Score : [0.54186]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1227   56]
 [ 114   13]]
              precision    recall  f1-score   support

       0: 정상       0.91      0.96      0.94      1283
       1: 이상       0.19      0.10      0.13       127

    accuracy                           0.88      1410
   macro avg       0.55      0.53      0.53      1410
weighted avg       0.85      0.88      0.86      1410

Epoch [4], Train Loss : [6.81508] Val Loss : [7.48838] Val F1 Score : [0.53393]
Epoch 00005: reducing learning rate of group 0 to 5.0000e-03.


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1210   73]
 [ 102   25]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.94      0.93      1283
       1: 이상       0.26      0.20      0.22       127

    accuracy                           0.88      1410
   macro avg       0.59      0.57      0.58      1410
weighted avg       0.86      0.88      0.87      1410

Epoch [5], Train Loss : [6.70892] Val Loss : [7.34537] Val F1 Score : [0.57739]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1200   83]
 [ 104   23]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.94      0.93      1283
       1: 이상       0.22      0.18      0.20       127

    accuracy                           0.87      1410
   macro avg       0.57      0.56      0.56      1410
weighted avg       0.86      0.87      0.86      1410

Epoch [6], Train Loss : [6.58332] Val Loss : [7.43783] Val F1 Score : [0.56257]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1189   94]
 [  98   29]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.93      0.93      1283
       1: 이상       0.24      0.23      0.23       127

    accuracy                           0.86      1410
   macro avg       0.58      0.58      0.58      1410
weighted avg       0.86      0.86      0.86      1410

Epoch [7], Train Loss : [6.49183] Val Loss : [7.41757] Val F1 Score : [0.57865]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1225   58]
 [ 107   20]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.95      0.94      1283
       1: 이상       0.26      0.16      0.20       127

    accuracy                           0.88      1410
   macro avg       0.59      0.56      0.57      1410
weighted avg       0.86      0.88      0.87      1410

Epoch [8], Train Loss : [6.45169] Val Loss : [7.33360] Val F1 Score : [0.56601]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1221   62]
 [ 104   23]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.95      0.94      1283
       1: 이상       0.27      0.18      0.22       127

    accuracy                           0.88      1410
   macro avg       0.60      0.57      0.58      1410
weighted avg       0.86      0.88      0.87      1410

Epoch [9], Train Loss : [6.35807] Val Loss : [7.48454] Val F1 Score : [0.57667]
Epoch 00010: reducing learning rate of group 0 to 2.5000e-03.


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1182  101]
 [  97   30]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.92      0.92      1283
       1: 이상       0.23      0.24      0.23       127

    accuracy                           0.86      1410
   macro avg       0.58      0.58      0.58      1410
weighted avg       0.86      0.86      0.86      1410

Epoch [10], Train Loss : [6.17124] Val Loss : [7.49927] Val F1 Score : [0.57764]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1178  105]
 [  93   34]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.92      0.92      1283
       1: 이상       0.24      0.27      0.26       127

    accuracy                           0.86      1410
   macro avg       0.59      0.59      0.59      1410
weighted avg       0.87      0.86      0.86      1410

Epoch [11], Train Loss : [6.03799] Val Loss : [7.57359] Val F1 Score : [0.58906]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1201   82]
 [  98   29]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.94      0.93      1283
       1: 이상       0.26      0.23      0.24       127

    accuracy                           0.87      1410
   macro avg       0.59      0.58      0.59      1410
weighted avg       0.86      0.87      0.87      1410

Epoch [12], Train Loss : [5.92684] Val Loss : [7.70827] Val F1 Score : [0.58699]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1212   71]
 [  98   29]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.94      0.93      1283
       1: 이상       0.29      0.23      0.26       127

    accuracy                           0.88      1410
   macro avg       0.61      0.59      0.60      1410
weighted avg       0.87      0.88      0.87      1410

Epoch [13], Train Loss : [5.97168] Val Loss : [7.67903] Val F1 Score : [0.59517]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1169  114]
 [  94   33]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.91      0.92      1283
       1: 이상       0.22      0.26      0.24       127

    accuracy                           0.85      1410
   macro avg       0.58      0.59      0.58      1410
weighted avg       0.86      0.85      0.86      1410

Epoch [14], Train Loss : [5.85456] Val Loss : [8.03380] Val F1 Score : [0.57959]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1178  105]
 [  95   32]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.92      0.92      1283
       1: 이상       0.23      0.25      0.24       127

    accuracy                           0.86      1410
   macro avg       0.58      0.59      0.58      1410
weighted avg       0.86      0.86      0.86      1410

Epoch [15], Train Loss : [5.84043] Val Loss : [7.87844] Val F1 Score : [0.58209]
Epoch 00016: reducing learning rate of group 0 to 1.2500e-03.


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1192   91]
 [  98   29]]
              precision    recall  f1-score   support

       0: 정상       0.92      0.93      0.93      1283
       1: 이상       0.24      0.23      0.23       127

    accuracy                           0.87      1410
   macro avg       0.58      0.58      0.58      1410
weighted avg       0.86      0.87      0.86      1410

Epoch [16], Train Loss : [5.62109] Val Loss : [7.92718] Val F1 Score : [0.58068]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1215   68]
 [  97   30]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.95      0.94      1283
       1: 이상       0.31      0.24      0.27       127

    accuracy                           0.88      1410
   macro avg       0.62      0.59      0.60      1410
weighted avg       0.87      0.88      0.88      1410

Epoch [17], Train Loss : [5.63476] Val Loss : [7.93406] Val F1 Score : [0.60154]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1188   95]
 [  95   32]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93      1283
       1: 이상       0.25      0.25      0.25       127

    accuracy                           0.87      1410
   macro avg       0.59      0.59      0.59      1410
weighted avg       0.87      0.87      0.87      1410

Epoch [18], Train Loss : [5.45061] Val Loss : [8.13204] Val F1 Score : [0.58896]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1184   99]
 [  92   35]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.92      0.93      1283
       1: 이상       0.26      0.28      0.27       127

    accuracy                           0.86      1410
   macro avg       0.59      0.60      0.60      1410
weighted avg       0.87      0.86      0.87      1410

Epoch [19], Train Loss : [5.56493] Val Loss : [8.02156] Val F1 Score : [0.59678]
Epoch 00020: reducing learning rate of group 0 to 6.2500e-04.


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1187   96]
 [  94   33]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93      1283
       1: 이상       0.26      0.26      0.26       127

    accuracy                           0.87      1410
   macro avg       0.59      0.59      0.59      1410
weighted avg       0.87      0.87      0.87      1410

Epoch [20], Train Loss : [5.48639] Val Loss : [8.09007] Val F1 Score : [0.59185]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1220   63]
 [  98   29]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.95      0.94      1283
       1: 이상       0.32      0.23      0.26       127

    accuracy                           0.89      1410
   macro avg       0.62      0.59      0.60      1410
weighted avg       0.87      0.89      0.88      1410

Epoch [21], Train Loss : [5.43143] Val Loss : [8.00557] Val F1 Score : [0.60147]
Epoch 00022: reducing learning rate of group 0 to 3.1250e-04.


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1197   86]
 [  95   32]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93      1283
       1: 이상       0.27      0.25      0.26       127

    accuracy                           0.87      1410
   macro avg       0.60      0.59      0.60      1410
weighted avg       0.87      0.87      0.87      1410

Epoch [22], Train Loss : [5.32244] Val Loss : [8.06945] Val F1 Score : [0.59547]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1192   91]
 [  92   35]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93      1283
       1: 이상       0.28      0.28      0.28       127

    accuracy                           0.87      1410
   macro avg       0.60      0.60      0.60      1410
weighted avg       0.87      0.87      0.87      1410

Epoch [23], Train Loss : [5.26412] Val Loss : [8.22623] Val F1 Score : [0.60270]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1183  100]
 [  93   34]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.92      0.92      1283
       1: 이상       0.25      0.27      0.26       127

    accuracy                           0.86      1410
   macro avg       0.59      0.59      0.59      1410
weighted avg       0.87      0.86      0.86      1410

Epoch [24], Train Loss : [5.20228] Val Loss : [8.16057] Val F1 Score : [0.59256]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1193   90]
 [  94   33]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93      1283
       1: 이상       0.27      0.26      0.26       127

    accuracy                           0.87      1410
   macro avg       0.60      0.59      0.60      1410
weighted avg       0.87      0.87      0.87      1410

Epoch [25], Train Loss : [5.34315] Val Loss : [8.13448] Val F1 Score : [0.59620]
Epoch 00026: reducing learning rate of group 0 to 1.5625e-04.


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1203   80]
 [  93   34]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.94      0.93      1283
       1: 이상       0.30      0.27      0.28       127

    accuracy                           0.88      1410
   macro avg       0.61      0.60      0.61      1410
weighted avg       0.87      0.88      0.87      1410

Epoch [26], Train Loss : [5.18882] Val Loss : [8.16713] Val F1 Score : [0.60754]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1196   87]
 [  93   34]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93      1283
       1: 이상       0.28      0.27      0.27       127

    accuracy                           0.87      1410
   macro avg       0.60      0.60      0.60      1410
weighted avg       0.87      0.87      0.87      1410

Epoch [27], Train Loss : [5.23520] Val Loss : [8.28811] Val F1 Score : [0.60210]


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1195   88]
 [  94   33]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93      1283
       1: 이상       0.27      0.26      0.27       127

    accuracy                           0.87      1410
   macro avg       0.60      0.60      0.60      1410
weighted avg       0.87      0.87      0.87      1410

Epoch [28], Train Loss : [5.11283] Val Loss : [8.19312] Val F1 Score : [0.59768]
Epoch 00029: reducing learning rate of group 0 to 7.8125e-05.


  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

[[1193   90]
 [  92   35]]
              precision    recall  f1-score   support

       0: 정상       0.93      0.93      0.93      1283
       1: 이상       0.28      0.28      0.28       127

    accuracy                           0.87      1410
   macro avg       0.60      0.60      0.60      1410
weighted avg       0.87      0.87      0.87      1410

Epoch [29], Train Loss : [5.24749] Val Loss : [8.20219] Val F1 Score : [0.60345]
Student Train Best Score는 0.6075387063402297 입니다.
부분학습 종료


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[  6 152]
 [  0  10]]
              precision    recall  f1-score   support

       0: 정상       1.00      0.04      0.07       158
       1: 이상       0.06      1.00      0.12        10

    accuracy                           0.10       168
   macro avg       0.53      0.52      0.09       168
weighted avg       0.94      0.10      0.08       168

Epoch [0], Train Loss : [11.37188] Val Loss : [9.65049] Val F1 Score : [0.09472]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[128  30]
 [  7   3]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.81      0.87       158
       1: 이상       0.09      0.30      0.14        10

    accuracy                           0.78       168
   macro avg       0.52      0.56      0.51       168
weighted avg       0.90      0.78      0.83       168

Epoch [1], Train Loss : [5.56644] Val Loss : [5.88322] Val F1 Score : [0.50663]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[140  18]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.89      0.92       158
       1: 이상       0.10      0.20      0.13        10

    accuracy                           0.85       168
   macro avg       0.52      0.54      0.52       168
weighted avg       0.90      0.85      0.87       168

Epoch [2], Train Loss : [4.46987] Val Loss : [4.70732] Val F1 Score : [0.52418]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[148  10]
 [  7   3]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.94      0.95       158
       1: 이상       0.23      0.30      0.26        10

    accuracy                           0.90       168
   macro avg       0.59      0.62      0.60       168
weighted avg       0.91      0.90      0.90       168

Epoch [3], Train Loss : [4.27028] Val Loss : [4.67239] Val F1 Score : [0.60328]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[147  11]
 [  7   3]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.93      0.94       158
       1: 이상       0.21      0.30      0.25        10

    accuracy                           0.89       168
   macro avg       0.58      0.62      0.60       168
weighted avg       0.91      0.89      0.90       168

Epoch [4], Train Loss : [3.80073] Val Loss : [5.02419] Val F1 Score : [0.59615]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[149   9]
 [  7   3]]
              precision    recall  f1-score   support

       0: 정상       0.96      0.94      0.95       158
       1: 이상       0.25      0.30      0.27        10

    accuracy                           0.90       168
   macro avg       0.60      0.62      0.61       168
weighted avg       0.91      0.90      0.91       168

Epoch [5], Train Loss : [3.47480] Val Loss : [5.14325] Val F1 Score : [0.61089]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[150   8]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.95      0.95       158
       1: 이상       0.20      0.20      0.20        10

    accuracy                           0.90       168
   macro avg       0.57      0.57      0.57       168
weighted avg       0.90      0.90      0.90       168

Epoch [6], Train Loss : [3.28078] Val Loss : [5.35782] Val F1 Score : [0.57468]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[149   9]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.94      0.95       158
       1: 이상       0.18      0.20      0.19        10

    accuracy                           0.90       168
   macro avg       0.57      0.57      0.57       168
weighted avg       0.90      0.90      0.90       168

Epoch [7], Train Loss : [2.98816] Val Loss : [5.66701] Val F1 Score : [0.56825]
Epoch 00008: reducing learning rate of group 0 to 5.0000e-03.


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[150   8]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.95      0.95       158
       1: 이상       0.20      0.20      0.20        10

    accuracy                           0.90       168
   macro avg       0.57      0.57      0.57       168
weighted avg       0.90      0.90      0.90       168

Epoch [8], Train Loss : [2.83258] Val Loss : [5.48722] Val F1 Score : [0.57468]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[150   8]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.95      0.95       158
       1: 이상       0.20      0.20      0.20        10

    accuracy                           0.90       168
   macro avg       0.57      0.57      0.57       168
weighted avg       0.90      0.90      0.90       168

Epoch [9], Train Loss : [2.66555] Val Loss : [5.37602] Val F1 Score : [0.57468]
Epoch 00010: reducing learning rate of group 0 to 2.5000e-03.


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[149   9]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.94      0.95       158
       1: 이상       0.18      0.20      0.19        10

    accuracy                           0.90       168
   macro avg       0.57      0.57      0.57       168
weighted avg       0.90      0.90      0.90       168

Epoch [10], Train Loss : [2.57970] Val Loss : [5.19107] Val F1 Score : [0.56825]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[149   9]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.94      0.95       158
       1: 이상       0.18      0.20      0.19        10

    accuracy                           0.90       168
   macro avg       0.57      0.57      0.57       168
weighted avg       0.90      0.90      0.90       168

Epoch [11], Train Loss : [2.54147] Val Loss : [5.07995] Val F1 Score : [0.56825]
Epoch 00012: reducing learning rate of group 0 to 1.2500e-03.


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[146  12]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.92      0.94       158
       1: 이상       0.14      0.20      0.17        10

    accuracy                           0.88       168
   macro avg       0.55      0.56      0.55       168
weighted avg       0.90      0.88      0.89       168

Epoch [12], Train Loss : [2.40727] Val Loss : [5.00592] Val F1 Score : [0.55128]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[145  13]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.92      0.93       158
       1: 이상       0.13      0.20      0.16        10

    accuracy                           0.88       168
   macro avg       0.54      0.56      0.55       168
weighted avg       0.90      0.88      0.89       168

Epoch [13], Train Loss : [2.44713] Val Loss : [4.98087] Val F1 Score : [0.54624]
Epoch 00014: reducing learning rate of group 0 to 6.2500e-04.


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [14], Train Loss : [2.40187] Val Loss : [4.97561] Val F1 Score : [0.53686]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [15], Train Loss : [2.55687] Val Loss : [4.97530] Val F1 Score : [0.53686]
Epoch 00016: reducing learning rate of group 0 to 3.1250e-04.


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [16], Train Loss : [2.41495] Val Loss : [4.94202] Val F1 Score : [0.53686]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [17], Train Loss : [2.52805] Val Loss : [4.92508] Val F1 Score : [0.53686]
Epoch 00018: reducing learning rate of group 0 to 1.5625e-04.


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [18], Train Loss : [2.38172] Val Loss : [4.91893] Val F1 Score : [0.53686]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [19], Train Loss : [2.36277] Val Loss : [4.89566] Val F1 Score : [0.53686]
Epoch 00020: reducing learning rate of group 0 to 7.8125e-05.


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [20], Train Loss : [2.40045] Val Loss : [4.89112] Val F1 Score : [0.53686]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [21], Train Loss : [2.35862] Val Loss : [4.89619] Val F1 Score : [0.53686]
Epoch 00022: reducing learning rate of group 0 to 3.9063e-05.


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [22], Train Loss : [2.53690] Val Loss : [4.91124] Val F1 Score : [0.53686]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [23], Train Loss : [2.44637] Val Loss : [4.89904] Val F1 Score : [0.53686]
Epoch 00024: reducing learning rate of group 0 to 1.9531e-05.


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [24], Train Loss : [2.38568] Val Loss : [4.89885] Val F1 Score : [0.53686]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [25], Train Loss : [2.38832] Val Loss : [4.89228] Val F1 Score : [0.53686]
Epoch 00026: reducing learning rate of group 0 to 9.7656e-06.


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [26], Train Loss : [2.30780] Val Loss : [4.88370] Val F1 Score : [0.53686]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [27], Train Loss : [2.36153] Val Loss : [4.86730] Val F1 Score : [0.53686]
Epoch 00028: reducing learning rate of group 0 to 4.8828e-06.


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [28], Train Loss : [2.48474] Val Loss : [4.86479] Val F1 Score : [0.53686]


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[[143  15]
 [  8   2]]
              precision    recall  f1-score   support

       0: 정상       0.95      0.91      0.93       158
       1: 이상       0.12      0.20      0.15        10

    accuracy                           0.86       168
   macro avg       0.53      0.55      0.54       168
weighted avg       0.90      0.86      0.88       168

Epoch [29], Train Loss : [2.40450] Val Loss : [4.85624] Val F1 Score : [0.53686]
Epoch 00030: reducing learning rate of group 0 to 2.4414e-06.
Student Train Best Score는 0.6108859293572669 입니다.
부분학습 종료
전체 학습 종료


In [943]:
def choose_threshold(model, val_loader, device):
    model.to(device)
    model.eval()
    
#     thresholds = [0.1, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
    thresholds = [0.05, 0.1, 0.15, 0.2, 0.25, 0.3]

    pred_labels = []
    true_labels = []
    
    best_score = 0
    best_thr = None
    with torch.no_grad():
        for _, x_s, y in tqdm(iter(val_loader)):
            x_s = x_s.float().to(device)
            y = y.float().to(device)
            
            model_pred = model(x_s)
            
            model_pred = model_pred.squeeze(1).to('cpu')
            pred_labels += model_pred.tolist()
            true_labels += y.tolist()
        
        for threshold in thresholds:
            pred_labels_thr = np.where(np.array(pred_labels) > threshold, 1, 0)
            score_thr = competition_metric(true_labels, pred_labels_thr)
            cf1 = confusion_matrix(true_labels, pred_labels_thr)  

#             print(cf1)
#             print(classification_report(true_labels, pred_labels_thr, target_names=["0: 정상", "1: 이상"]))

            if best_score < score_thr:
                best_score = score_thr
                best_thr = threshold
                
    return best_thr, best_score

In [944]:
# for a, b in zip(students, s_val_loaders):
    
#     print(list(b))
    
for a, b, c, d, e, f in zip(s_train_loaders, s_val_loaders, train_X_list, test_list, teachers, students):
    train_col_num = len(c.columns)
    test_stage_features = d.iloc[:,:-1].columns
    test_col_num = len(test_stage_features)


    choose_threshold(f, b, device)
    best_threshold, best_score = choose_threshold(f, b, device)
    choose_threshold_result = f'Best Threshold : [{best_threshold}], Score : [{best_score:.5f}]'
    print(choose_threshold_result)
    
    print("부분 작업 종료")

print("전체 작업 종료")

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

Best Threshold : [0.3], Score : [0.53977]
부분 작업 종료


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

Best Threshold : [0.25], Score : [0.51202]
부분 작업 종료


  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

Best Threshold : [0.3], Score : [0.58700]
부분 작업 종료


  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

Best Threshold : [0.25], Score : [0.56078]
부분 작업 종료
전체 작업 종료


In [945]:
test_2

encoder__x1_2008  encoder__x1_2009  encoder__x1_2010  encoder__x1_2011  \
0                 0.0               0.0               1.0               0.0   
1                 0.0               0.0               0.0               0.0   
2                 0.0               0.0               0.0               0.0   
3                 0.0               0.0               0.0               0.0   
4                 0.0               1.0               0.0               0.0   
..                ...               ...               ...               ...   
988               0.0               0.0               0.0               0.0   
989               0.0               0.0               0.0               0.0   
990               0.0               0.0               0.0               0.0   
991               1.0               0.0               0.0               0.0   
992               0.0               0.0               0.0               0.0   

     encoder__x1_2012  encoder__x1_2013  encoder__x1_2014  encoder__x1_2015  \
0                 0.0               0.0               0.0               0.0   
1                 0.0               1.0               0.0               0.0   
2                 0.0               0.0               1.0               0.0   
3                 0.0               0.0               1.0               0.0   
4                 0.0               0.0               0.0               0.0   
..                ...               ...               ...               ...   
988               0.0               1.0               0.0               0.0   
989               0.0               0.0               1.0               0.0   
990               0.0               1.0               0.0               0.0   
991               0.0               0.0               0.0               0.0   
992               0.0               1.0               0.0               0.0   

     encoder__x1_2016  encoder__x1_2017  ...        FE       H2O        MN  \
0                 0.0               0.0  ... -0.294593 -0.077342 -0.352471   
1                 0.0               0.0  ...  0.432480 -0.077342 -0.352471   
2                 0.0               0.0  ... -0.294593 -0.077342 -0.352471   
3                 0.0               0.0  ...  0.143751 -0.077342 -0.352471   
4                 0.0               0.0  ...  1.695458 -0.077342 -0.352471   
..                ...               ...  ...       ...       ...       ...   
988               0.0               0.0  ...  0.491684 -0.077342 -0.352471   
989               0.0               0.0  ... -0.294593 -0.077342 -0.352471   
990               0.0               0.0  ...  0.694531 -0.077342 -0.352471   
991               0.0               0.0  ...  1.938797 -0.077342  2.186212   
992               0.0               0.0  ... -0.889388 -0.077342 -0.352471   

           MO        NI        TI         V       V40        ZN   order  
0   -0.375764 -0.144333 -0.131016 -0.083807 -0.737903  1.041387     2.0  
1   -0.375764 -0.144333 -0.131016 -0.083807  0.986401 -0.183985     4.0  
2    0.901335 -0.144333 -0.131016 -0.083807  0.736600 -0.279014    19.0  
3   -0.375764 -0.144333 -0.131016 -0.083807 -0.684101  0.591250    21.0  
4   -0.375764 -0.144333 -0.131016 -0.083807  0.388139  0.031080    38.0  
..        ...       ...       ...       ...       ...       ...     ...  
988 -0.375764 -0.144333  7.917125 -0.083807  0.598527  0.176124  6017.0  
989 -0.375764 -0.144333 -0.131016 -0.083807 -0.737903  0.676276  6020.0  
990 -0.375764 -0.144333 -0.131016 -0.083807  0.040763  0.431202  6021.0  
991 -0.375764 -0.144333 -0.131016 -0.083807 -1.360026 -0.404052  6028.0  
992 -0.375764 -0.144333 -0.131016 -0.083807 -0.052420 -0.138971  6039.0  

[993 rows x 31 columns]

In [946]:
test_loaders = []

for i in test_list:

    test_dataset = CustomDataset(i.iloc[:,:-1], None, False)
    test_loader = DataLoader(test_dataset, batch_size = CFG['BATCH_SIZE'], shuffle=False)
    test_loaders.append(test_loader)

# print(list(test_loaders[0]))
    

[tensor([[ 0.0000,  0.0000,  0.0000,  ..., -0.1559, -0.8498, -0.3947],
        [ 0.0000,  0.0000,  0.0000,  ..., -0.1559,  1.7224,  0.1522],
        [ 0.0000,  0.0000,  0.0000,  ..., -0.1559,  1.1441, -0.9415],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ..., -0.1559,  1.1309, -0.9697],
        [ 0.0000,  0.0000,  0.0000,  ..., -0.1559, -0.2682, -0.7048],
        [ 0.0000,  0.0000,  0.0000,  ..., -0.1559, -0.2210, -1.0768]]), tensor([[ 0.0000,  0.0000,  0.0000,  ..., -0.1559, -0.4844, -0.2368],
        [ 0.0000,  0.0000,  0.0000,  ..., -0.1559,  0.6963,  1.3643],
        [ 0.0000,  0.0000,  0.0000,  ..., -0.1559,  0.4697,  2.0351],
        ...,
        [ 0.0000,  0.0000,  1.0000,  ..., -0.1559,  0.5909,  1.0204],
        [ 0.0000,  1.0000,  0.0000,  ..., -0.1559, -0.4600, -0.0903],
        [ 0.0000,  0.0000,  0.0000,  ..., -0.1559,  0.4047, -0.5018]]), tensor([[ 0.0000,  0.0000,  0.0000,  ..., -0.1559, -0.0502,  0.3495],
        [ 0.0000,  0.0000,  0.0000,  ..., -0.1559,  0.9775,

In [947]:
# test_datasets = CustomDataset(test, None, False)
# test_loaders = DataLoader(test_datasets, batch_size = CFG['BATCH_SIZE'], shuffle=False)

In [948]:
def inference(model, test_loader, threshold, device):
    model.to(device)
    model.eval()
    # .eval함수는 evaluation 과정에서 사용하지 말아야 하는 layer들을 알아서 off 시키는 함수
    
    test_predict = []
    with torch.no_grad():
        for x in tqdm(test_loader):
            x = x.float().to(device)
            model_pred = model(x)

            model_pred = model_pred.squeeze(1).to('cpu')
            test_predict += model_pred
        
    test_predict = np.where(np.array(test_predict) > threshold, 1, 0)  
    # threshhold 보다 큰 값을 찾아서 1로 바꾸고, 아닌 것은 0으로 변경해라
    print('Done.')
    return test_predict

In [949]:
pred_list = []
order_list = []
for a, b, c in zip(students, test_loaders, test_list):
    preds = inference(a, b, best_threshold, device)
    print(len(preds))
    print(len(c.order.tolist()))
    pred_list.extend(preds)
    order_list.extend(c.order.tolist())
print(len(pred_list))
print(len(order_list))
    

  0%|          | 0/7 [00:00<?, ?it/s]

Done.
1667
1667


  0%|          | 0/4 [00:00<?, ?it/s]

Done.
993
993


  0%|          | 0/12 [00:00<?, ?it/s]

Done.
3021
3021


  0%|          | 0/2 [00:00<?, ?it/s]

Done.
360
360
6041
6041


In [950]:
{"예측값": pred_list, "순서": order_list}

{'예측값': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0

In [951]:
result = pd.DataFrame({"예측값": pred_list, "순서": order_list})
result.sort_values(by=["순서"], inplace=True)
result

예측값      순서
0       0     0.0
2660    0     1.0
1667    0     2.0
2661    1     3.0
1668    0     4.0
...   ...     ...
5678    0  6036.0
5679    0  6037.0
5680    0  6038.0
2659    0  6039.0
1666    1  6040.0

[6041 rows x 2 columns]

In [952]:
final_result = result["예측값"].tolist()
final_result

[0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,


In [953]:

# preds = inference(best_student_model, test_loaders, best_threshold, device)

In [954]:
submit = pd.read_csv('./data/sample_submission.csv')
submit['Y_LABEL'] = final_result
submit.head()

ID  Y_LABEL
0  TEST_0000        0
1  TEST_0001        0
2  TEST_0002        0
3  TEST_0003        1
4  TEST_0004        0

In [955]:
pred_cnt = tuple(submit["Y_LABEL"].value_counts())
a, b = pred_cnt
r = f"정상값 개수 : {a}, 이상값 개수 : {b}"
print(r)

정상값 개수 : 5386, 이상값 개수 : 655


In [956]:
submit.to_csv(f'./submits/submit{file_version}.csv', index=False)

In [957]:
record = {"ver": file_version, "CFG": CFG, "Val_result": choose_threshold_result, "pred_cnt": r}
record

{'ver': 53,
 'CFG': {'EPOCHS': 30,
  'LEARNING_RATE': 0.01,
  'BATCH_SIZE': 256,
  'SEED': 43,
  'log_transform_turn': 1,
  'skew_cut': 0.01,
  'vif_cut': 10,
  'corr_cut': 0.004,
  'outlier_corr_cut': 100,
  'T_Thresh': 0.3,
  'S_Thresh': 0.325,
  'reduct': 'sum',
  'drop_rate': 0.2},
 'Val_result': 'Best Threshold : [0.25], Score : [0.56078]',
 'pred_cnt': '정상값 개수 : 5386, 이상값 개수 : 655'}